import { useEffect, useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Booking, BookingEvent, getClientAccount, updateClientAccountBooking } from '../src/api';
import { secureStorage } from '../src/storage';
import { colors, radius } from '../src/theme';

const status:Record<string,string>={new:'Received',confirmed:'Confirmed',assigned:'Crew assigned',on_the_way:'On the way',in_progress:'In progress',completed:'Completed',cancelled:'Cancelled',change_requested:'Change requested'};
export default function AccountOrderScreen(){
 const {id}=useLocalSearchParams<{id?:string}>();const[booking,setBooking]=useState<Booking|null>(null);const[events,setEvents]=useState<BookingEvent[]>([]);const[token,setToken]=useState('');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[pickup,setPickup]=useState('');const[destination,setDestination]=useState('');const[date,setDate]=useState('');const[time,setTime]=useState('');const[notes,setNotes]=useState('');const[quoteNote,setQuoteNote]=useState('');
 const apply=(b:Booking,e:BookingEvent[]=[])=>{setBooking(b);setEvents(e);setPickup(b.pickup);setDestination(b.destination);setDate(b.preferred_date);setTime(b.preferred_time);setNotes(b.notes||'')};
 const load=async()=>{setBusy(true);try{const session=await secureStorage.getClientSession();if(!session.token)throw new Error('SESSION_INVALID');setToken(session.token);const r=await getClientAccount(session.token,String(id||''));apply(r.booking,r.events||[]);setMsg('')}catch(e){setMsg(e instanceof Error?e.message:'Error')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[id]);
 const act=async(bookingAction:string,patch:Record<string,unknown>={})=>{if(!booking||!token)return;setBusy(true);try{const r=await updateClientAccountBooking(token,booking.id,bookingAction,patch);apply(r.booking,r.events||[]);setMsg('✓')}catch(e){setMsg(e instanceof Error?e.message:'Error')}finally{setBusy(false)}};
 if(!booking)return <ScrollView contentContainerStyle={s.wrap} refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>}><Text style={s.title}>Muuttobotti v2</Text><Text>{msg||'Loading…'}</Text><TouchableOpacity style={s.secondary} onPress={()=>router.back()}><Text style={s.secondaryText}>Back</Text></TouchableOpacity></ScrollView>;
 const quotePending=booking.quote_status==='pending'&&Number(booking.quoted_price||0)>0;
 return <ScrollView contentContainerStyle={s.wrap} refreshControl={<RefreshControl refreshing={busy} onRefresh={load} tintColor={colors.ink}/>} keyboardShouldPersistTaps="handled">
  <View style={s.hero}><Text style={s.kicker}>ACCOUNT ORDER · {booking.id}</Text><Text style={s.title}>{status[booking.status]||booking.status}</Text><Text style={s.copy}>{booking.preferred_date} {booking.preferred_time} · {booking.service}</Text><View style={s.route}><Text style={s.routeText}>{booking.pickup}</Text><Text style={s.routeArrow}>↓</Text><Text style={s.routeText}>{booking.destination}</Text></View></View>
  {quotePending&&<View style={s.offer}><Text style={s.offerLabel}>PRICE OFFER</Text><Text style={s.offerPrice}>{Number(booking.quoted_price).toFixed(2)} €</Text><Text style={s.offerCopy}>{booking.admin_note||'Confirm the price or request a change.'}</Text><TouchableOpacity style={s.primary} onPress={()=>act('accept_quote')}><Text style={s.primaryText}>Accept price</Text></TouchableOpacity><TextInput multiline value={quoteNote} onChangeText={setQuoteNote} placeholder="Request a price change…" style={[s.input,s.textarea]}/><TouchableOpacity style={s.secondary} onPress={()=>act('reject_quote',{note:quoteNote})}><Text style={s.secondaryText}>Request change</Text></TouchableOpacity></View>}
  {!!booking.assigned_worker&&<View style={s.crew}><Text style={s.kicker}>CREW</Text><Text style={s.crewName}>{booking.assigned_worker}</Text><Text style={s.copy}>{booking.assigned_worker_phone||''}</Text></View>}
  <View style={s.panel}><Text style={s.section}>Timeline</Text>{events.slice().reverse().map((e,i)=><View key={`${e.event_id||i}-${e.created_at}`} style={s.event}><View style={s.dot}/><View style={{flex:1}}><Text style={s.eventTitle}>{status[e.status]||e.event_type}</Text><Text style={s.eventMeta}>{new Date(e.created_at).toLocaleString()} · {e.source}</Text>{!!e.note&&<Text style={s.eventNote}>{e.note}</Text>}</View></View>)}</View>
  {['new','confirmed','assigned','change_requested'].includes(booking.status)&&<View style={s.panel}><Text style={s.section}>Modify booking</Text><Field label="Pickup" value={pickup} onChangeText={setPickup}/><Field label="Destination" value={destination} onChangeText={setDestination}/><View style={s.two}><Field label="Date YYYY-MM-DD" value={date} onChangeText={setDate}/><Field label="Time HH:MM" value={time} onChangeText={setTime}/></View><TextInput multiline value={notes} onChangeText={setNotes} placeholder="Notes" style={[s.input,s.textarea]}/><TouchableOpacity style={s.primary} onPress={()=>act('modify',{pickup,destination,date,time,notes})}><Text style={s.primaryText}>Send change request</Text></TouchableOpacity><TouchableOpacity style={s.danger} onPress={()=>act('cancel')}><Text style={s.dangerText}>Cancel booking</Text></TouchableOpacity></View>}
  {!!msg&&<Text style={s.msg}>{msg}</Text>}<TouchableOpacity style={s.secondary} onPress={()=>router.back()}><Text style={s.secondaryText}>Back to profile</Text></TouchableOpacity>
 </ScrollView>
}
function Field(props:any){return <View style={[s.field,props.style]}><Text style={s.label}>{props.label}</Text><TextInput {...props} style={s.input}/></View>}
const s=StyleSheet.create({wrap:{padding:16,paddingBottom:45,gap:11,backgroundColor:'#EEF3EE'},hero:{backgroundColor:'#06191F',borderRadius:radius.xl,padding:21},kicker:{color:'#C8FF36',fontSize:9,fontWeight:'950',letterSpacing:1},title:{color:'#fff',fontSize:31,fontWeight:'950',letterSpacing:-1,marginTop:6},copy:{color:'#A7BDB8',fontSize:12,lineHeight:18,marginTop:5},route:{marginTop:15,paddingTop:12,borderTopWidth:1,borderTopColor:'#24444C'},routeText:{color:'#fff',fontSize:13,fontWeight:'800'},routeArrow:{color:'#C8FF36',marginVertical:2},offer:{backgroundColor:'#F2FFE0',borderWidth:1,borderColor:'#CDEB91',borderRadius:radius.lg,padding:17},offerLabel:{color:'#607842',fontSize:9,fontWeight:'950',letterSpacing:1},offerPrice:{fontSize:37,fontWeight:'950',color:colors.ink,marginTop:3},offerCopy:{color:'#5F735A',fontSize:12,lineHeight:18,marginTop:4},crew:{backgroundColor:'#0C2E36',borderRadius:radius.lg,padding:17},crewName:{color:'#fff',fontSize:20,fontWeight:'950',marginTop:5},panel:{backgroundColor:'#fff',borderRadius:radius.lg,padding:16,borderWidth:1,borderColor:colors.line,gap:8},section:{color:colors.ink,fontSize:18,fontWeight:'950'},event:{flexDirection:'row',gap:9,paddingVertical:8,borderBottomWidth:1,borderBottomColor:'#EEF1EE'},dot:{width:9,height:9,borderRadius:5,backgroundColor:'#C8FF36',marginTop:4},eventTitle:{color:colors.ink,fontSize:12,fontWeight:'900'},eventMeta:{color:colors.muted,fontSize:9,marginTop:2},eventNote:{color:'#5E716C',fontSize:10,lineHeight:15,marginTop:3},field:{backgroundColor:'#fff',borderWidth:1,borderColor:colors.line,borderRadius:14,paddingHorizontal:12,paddingTop:9},label:{fontSize:9,fontWeight:'950',color:'#6C807A',textTransform:'uppercase'},input:{minHeight:40,color:colors.ink,fontWeight:'700',padding:0},textarea:{minHeight:80,textAlignVertical:'top',backgroundColor:'#fff',borderWidth:1,borderColor:colors.line,borderRadius:14,padding:12},two:{flexDirection:'row',gap:7},primary:{minHeight:51,borderRadius:14,backgroundColor:'#C8FF36',alignItems:'center',justifyContent:'center',marginTop:8},primaryText:{color:colors.ink,fontWeight:'950'},secondary:{minHeight:48,borderRadius:14,borderWidth:1,borderColor:colors.line,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',marginTop:7},secondaryText:{color:colors.ink,fontWeight:'900'},danger:{minHeight:48,borderRadius:14,backgroundColor:'#FAE8E8',alignItems:'center',justifyContent:'center',marginTop:7},dangerText:{color:colors.danger,fontWeight:'950'},msg:{color:'#4E7748',fontSize:12,fontWeight:'850'}})
