import { useEffect, useRef, useState } from 'react';
import { router } from 'expo-router';
import { ActivityIndicator, Animated, KeyboardAvoidingView, Platform, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { getAdminBookings, getBooking } from '../src/api';
import { localeOptions, useLanguage } from '../src/i18n';
import { secureStorage } from '../src/storage';
import { colors, radius, shadow } from '../src/theme';

type Role='client'|'admin';
const copy={
fi:{welcome:'Kaikki muuttoon yhdessä sovelluksessa.',subtitle:'Laske hinta, varaa palvelu ja seuraa tilausta.',client:'Asiakas',admin:'Admin',clientTitle:'Avaa oma varaus',clientCopy:'Jos sinulla on jo varaus, kirjaudu varausnumerolla ja pääsykoodilla.',adminTitle:'Admin-kirjautuminen',adminCopy:'Vain Muuttobotin henkilöstölle.',bookingId:'Varausnumero',accessKey:'Pääsykoodi',adminToken:'Admin token',signIn:'Kirjaudu sisään',newCustomer:'Uusi asiakas?',continueGuest:'Aloita ilman kirjautumista',hint:'Pääsykoodi tulee varauksen yksityisen seurantalinkin mukana.',invalidClient:'Varausta ei löytynyt näillä tunnuksilla.',invalidAdmin:'Admin-kirjautuminen epäonnistui.'},
en:{welcome:'Everything for your move in one app.',subtitle:'Calculate price, book a service and track the order.',client:'Customer',admin:'Admin',clientTitle:'Open your booking',clientCopy:'If you already have a booking, sign in with the booking number and access code.',adminTitle:'Admin sign in',adminCopy:'For Muuttobotti staff only.',bookingId:'Booking number',accessKey:'Access code',adminToken:'Admin token',signIn:'Sign in',newCustomer:'New customer?',continueGuest:'Start without signing in',hint:'The access code is included in your private tracking link.',invalidClient:'No booking was found with these credentials.',invalidAdmin:'Admin sign in failed.'},
uk:{welcome:'Усе для переїзду в одному застосунку.',subtitle:'Розрахуйте ціну, забронюйте послугу та відстежуйте замовлення.',client:'Клієнт',admin:'Admin',clientTitle:'Відкрити замовлення',clientCopy:'Якщо замовлення вже є, увійдіть за номером і кодом доступу.',adminTitle:'Вхід адміністратора',adminCopy:'Лише для команди Muuttobotti.',bookingId:'Номер замовлення',accessKey:'Код доступу',adminToken:'Admin token',signIn:'Увійти',newCustomer:'Новий клієнт?',continueGuest:'Почати без входу',hint:'Код доступу міститься у приватному посиланні на відстеження.',invalidClient:'Замовлення з такими даними не знайдено.',invalidAdmin:'Не вдалося увійти до admin.'},
ru:{welcome:'Всё для переезда в одном приложении.',subtitle:'Рассчитай цену, забронируй услугу и отслеживай заказ.',client:'Клиент',admin:'Администратор',clientTitle:'Открыть свой заказ',clientCopy:'Если заказ уже есть, войди по номеру заказа и коду доступа.',adminTitle:'Вход администратора',adminCopy:'Только для команды Muuttobotti.',bookingId:'Номер заказа',accessKey:'Код доступа',adminToken:'Admin token',signIn:'Войти',newCustomer:'Новый клиент?',continueGuest:'Начать без входа',hint:'Код доступа находится в приватной ссылке отслеживания.',invalidClient:'Заказ с такими данными не найден.',invalidAdmin:'Не удалось войти в admin.'},
} as const;

export default function IndexScreen(){
  const {locale,setLocale}=useLanguage();const t=copy[locale];
  const [role,setRole]=useState<Role>('client');const [bookingId,setBookingId]=useState('');const [accessKey,setAccessKey]=useState('');const [adminToken,setAdminToken]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const fade=useRef(new Animated.Value(0)).current;const lift=useRef(new Animated.Value(16)).current;
  useEffect(()=>{Animated.parallel([Animated.timing(fade,{toValue:1,duration:430,useNativeDriver:true}),Animated.spring(lift,{toValue:0,damping:18,stiffness:150,useNativeDriver:true})]).start();void(async()=>{const[client,token]=await Promise.all([secureStorage.getClientCredentials(),secureStorage.getAdminToken()]);if(client.id)setBookingId(client.id);if(client.key)setAccessKey(client.key);if(token)setAdminToken(token)})();},[fade,lift]);

  const signIn=async()=>{setBusy(true);setMessage('');try{if(role==='client'){const id=bookingId.trim().toUpperCase(),key=accessKey.trim().toLowerCase();if(!id||!key)throw new Error(t.invalidClient);await getBooking(id,key);await secureStorage.setClientCredentials(id,key);router.replace({pathname:'/(client)/track',params:{id,key}});}else{const token=adminToken.trim();if(!token)throw new Error(t.invalidAdmin);await getAdminBookings(token);await secureStorage.setAdminToken(token);router.replace('/admin');}}catch(error){setMessage(error instanceof Error&&error.message?error.message:(role==='client'?t.invalidClient:t.invalidAdmin));}finally{setBusy(false)}};

  return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.wrap} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
    <Animated.View style={{opacity:fade,transform:[{translateY:lift}]}}>
      <View style={s.brandRow}><View style={s.logoRow}><View style={s.mark}><Text style={s.markText}>M</Text></View><View><Text style={s.logo}>Muuttobotti</Text><Text style={s.version}>MOBILE · V1</Text></View></View><View style={s.languages}>{localeOptions.map(item=><TouchableOpacity key={item.value} style={[s.lang,locale===item.value&&s.langActive]} onPress={()=>setLocale(item.value)}><Text style={[s.langText,locale===item.value&&s.langTextActive]}>{item.label}</Text></TouchableOpacity>)}</View></View>
      <View style={s.hero}><View style={s.trust}><Text style={s.star}>★</Text><Text style={s.trustText}>{locale==='en'?'4.9/5 · 34 Google reviews':'4,9/5 · 34 Google'}</Text></View><Text style={s.title}>{t.welcome}</Text><Text style={s.copy}>{t.subtitle}</Text></View>
      <View style={s.loginCard}><View style={s.roleTabs}><TouchableOpacity style={[s.roleTab,role==='client'&&s.roleTabActive]} onPress={()=>{setRole('client');setMessage('')}}><Text style={[s.roleText,role==='client'&&s.roleTextActive]}>{t.client}</Text></TouchableOpacity><TouchableOpacity style={[s.roleTab,role==='admin'&&s.roleTabActive]} onPress={()=>{setRole('admin');setMessage('')}}><Text style={[s.roleText,role==='admin'&&s.roleTextActive]}>{t.admin}</Text></TouchableOpacity></View>
        <Text style={s.formTitle}>{role==='client'?t.clientTitle:t.adminTitle}</Text><Text style={s.formCopy}>{role==='client'?t.clientCopy:t.adminCopy}</Text>
        {role==='client'?<><Field label={t.bookingId} value={bookingId} onChangeText={setBookingId} autoCapitalize="characters" placeholder="MB-12AB34CD"/><Field label={t.accessKey} value={accessKey} onChangeText={setAccessKey} autoCapitalize="none" secureTextEntry placeholder="••••••••••••••••"/><Text style={s.hint}>{t.hint}</Text></>:<Field label={t.adminToken} value={adminToken} onChangeText={setAdminToken} autoCapitalize="none" secureTextEntry placeholder="••••••••••••••••"/>}
        {!!message&&<Text style={s.error}>{message}</Text>}<TouchableOpacity style={[s.primary,busy&&s.disabled]} disabled={busy} onPress={signIn}>{busy?<ActivityIndicator color={colors.ink}/>:<Text style={s.primaryText}>{t.signIn} →</Text>}</TouchableOpacity>
        {role==='client'&&<View style={s.guest}><Text style={s.guestLabel}>{t.newCustomer}</Text><TouchableOpacity style={s.secondary} onPress={()=>router.replace('/(client)')}><Text style={s.secondaryText}>{t.continueGuest}</Text></TouchableOpacity></View>}
      </View>
      <View style={s.security}><View style={s.securityDot}/><Text style={s.securityText}>HTTPS · SecureStore · private booking access</Text></View><Text style={s.footer}>Autochemix Oy · Y-tunnus 3543357-8</Text>
    </Animated.View>
  </ScrollView></KeyboardAvoidingView></SafeAreaView>;
}

function Field(props:any){return <View style={s.field}><Text style={s.label}>{props.label}</Text><TextInput {...props} placeholderTextColor="#738A87" style={s.input}/></View>}
const s=StyleSheet.create({
  safe:{flex:1,backgroundColor:colors.ink},flex:{flex:1},wrap:{flexGrow:1,padding:18,paddingBottom:32,backgroundColor:colors.ink},brandRow:{gap:13,marginTop:3},logoRow:{flexDirection:'row',alignItems:'center',gap:10},mark:{width:43,height:43,borderRadius:13,backgroundColor:colors.lime,alignItems:'center',justifyContent:'center'},markText:{color:colors.ink,fontWeight:'900',fontSize:20},logo:{color:'#fff',fontSize:23,fontWeight:'900'},version:{color:'#718C87',fontSize:9,fontWeight:'900',letterSpacing:1,marginTop:1},languages:{flexDirection:'row',gap:6},lang:{minWidth:43,height:34,borderRadius:10,borderWidth:1,borderColor:'#29464E',alignItems:'center',justifyContent:'center'},langActive:{backgroundColor:'#18353D',borderColor:'#45636A'},langText:{color:'#88A09D',fontWeight:'900',fontSize:11},langTextActive:{color:colors.lime},
  hero:{paddingTop:27,paddingBottom:23},trust:{alignSelf:'flex-start',flexDirection:'row',gap:6,alignItems:'center',backgroundColor:'#12313A',borderRadius:999,paddingHorizontal:10,paddingVertical:6},star:{color:colors.lime},trustText:{color:'#D5E2DF',fontSize:10,fontWeight:'800'},title:{color:'#fff',fontSize:37,lineHeight:40,fontWeight:'900',letterSpacing:-1.3,marginTop:13},copy:{color:'#A9BCB8',fontSize:15,lineHeight:23,marginTop:9},
  loginCard:{backgroundColor:'#F4F6F2',borderRadius:27,padding:18,gap:11,...shadow},roleTabs:{flexDirection:'row',backgroundColor:'#E4EAE2',borderRadius:15,padding:4,gap:4},roleTab:{flex:1,minHeight:44,borderRadius:12,alignItems:'center',justifyContent:'center'},roleTabActive:{backgroundColor:colors.ink},roleText:{color:'#6A7B77',fontSize:13,fontWeight:'900'},roleTextActive:{color:'#fff'},formTitle:{color:colors.ink,fontSize:24,fontWeight:'900',marginTop:4},formCopy:{color:'#667975',fontSize:13,lineHeight:20},field:{backgroundColor:'#fff',borderWidth:1,borderColor:'#DDE5DC',borderRadius:radius.md,paddingHorizontal:14,paddingTop:9,paddingBottom:7},label:{color:'#667A75',fontSize:9,fontWeight:'900',letterSpacing:.8,textTransform:'uppercase'},input:{minHeight:42,padding:0,color:colors.ink,fontSize:16,fontWeight:'700'},hint:{color:'#788985',fontSize:11,lineHeight:16},error:{color:colors.danger,fontSize:13,lineHeight:19,fontWeight:'700'},primary:{minHeight:56,borderRadius:radius.md,backgroundColor:colors.lime,alignItems:'center',justifyContent:'center'},primaryText:{color:colors.ink,fontSize:15,fontWeight:'900'},disabled:{opacity:.65},guest:{borderTopWidth:1,borderTopColor:'#DDE4DC',paddingTop:12,gap:8},guestLabel:{color:'#71827E',fontSize:11,fontWeight:'800',textAlign:'center'},secondary:{minHeight:49,borderRadius:radius.md,borderWidth:1,borderColor:'#CAD6CC',alignItems:'center',justifyContent:'center',backgroundColor:'#fff'},secondaryText:{color:colors.ink,fontSize:13,fontWeight:'900'},security:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7,marginTop:17},securityDot:{width:7,height:7,borderRadius:4,backgroundColor:colors.lime},securityText:{color:'#718C89',fontSize:9,fontWeight:'700'},footer:{color:'#5F7976',textAlign:'center',fontSize:9,marginTop:8},
});
