import { useEffect, useState } from 'react';
import DateTimePicker from '@expo/ui/community/datetime-picker';
import { useLocalSearchParams } from 'expo-router';
import { Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Booking, getBooking, updateClientBooking } from '../src/api';
import { useLanguage } from '../src/i18n';
import { secureStorage } from '../src/storage';
import { colors, radius } from '../src/theme';

const pad=(v:number)=>String(v).padStart(2,'0');
const dateString=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const timeString=(d:Date)=>`${pad(d.getHours())}:${pad(d.getMinutes())}`;
function fromDateTime(date:string,time:string){ const d=new Date(`${date || '2026-01-01'}T${time || '10:00'}:00`); return Number.isNaN(d.getTime())?new Date():d; }

export default function TrackScreen() {
  const params=useLocalSearchParams<{id?:string;key?:string}>();
  const {tr}=useLanguage();
  const [id,setId]=useState(''); const [key,setKey]=useState(''); const [booking,setBooking]=useState<Booking|null>(null);
  const [pickup,setPickup]=useState(''); const [destination,setDestination]=useState(''); const [date,setDate]=useState(''); const [time,setTime]=useState(''); const [notes,setNotes]=useState('');
  const [showDate,setShowDate]=useState(false); const [showTime,setShowTime]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');

  useEffect(()=>{ (async()=>{ const saved=await secureStorage.getClientCredentials(); const nextId=String(params.id||saved.id||'').toUpperCase(); const nextKey=String(params.key||saved.key||'').toLowerCase(); setId(nextId); setKey(nextKey); if(params.id&&params.key) setTimeout(()=>void loadWith(nextId,nextKey),0); })(); },[params.id,params.key]);

  const apply=(value:Booking)=>{ setBooking(value); setPickup(value.pickup); setDestination(value.destination); setDate(value.preferred_date); setTime(value.preferred_time); setNotes(value.notes||''); };
  const loadWith=async(nextId=id,nextKey=key)=>{ if(!nextId||!nextKey)return setMessage(tr('enterTracking')); setBusy(true);setMessage(''); try{const result=await getBooking(nextId.trim().toUpperCase(),nextKey.trim().toLowerCase());apply(result.booking);await secureStorage.setClientCredentials(nextId.trim().toUpperCase(),nextKey.trim().toLowerCase());}catch(error){setMessage(error instanceof Error?error.message:tr('enterTracking'));}finally{setBusy(false);} };
  const modify=async()=>{ if(!booking)return;setBusy(true);setMessage('');try{const result=await updateClientBooking(id,key,{action:'modify',pickup,destination,date,time,notes});apply(result.booking);setMessage('✓');}catch(error){setMessage(error instanceof Error?error.message:'Error');}finally{setBusy(false);} };
  const cancel=async()=>{if(!booking)return;setBusy(true);try{const result=await updateClientBooking(id,key,{action:'cancel'});apply(result.booking);}catch(error){setMessage(error instanceof Error?error.message:'Error');}finally{setBusy(false);} };

  const statusLabels:Record<string,string>={new:'Vastaanotettu',confirmed:'Vahvistettu',assigned:'Tekijä määritetty',in_progress:'Käynnissä',completed:'Valmis',cancelled:'Peruttu',change_requested:'Muutos pyydetty'};
  if(!booking)return <ScrollView contentContainerStyle={styles.wrap} keyboardShouldPersistTaps="handled"><Text style={styles.intro}>{tr('enterTracking')}</Text><Field label={tr('bookingNumber')} value={id} onChangeText={setId} autoCapitalize="characters" placeholder="MB-12AB34CD"/><Field label={tr('accessKey')} value={key} onChangeText={setKey} autoCapitalize="none"/><TouchableOpacity disabled={busy} onPress={()=>loadWith()} style={styles.primary}><Text style={styles.primaryText}>{busy?'…':tr('openBooking')}</Text></TouchableOpacity>{!!message&&<Text style={styles.message}>{message}</Text>}</ScrollView>;

  const dt=fromDateTime(date,time);
  return <ScrollView contentContainerStyle={styles.wrap} keyboardShouldPersistTaps="handled">
    <View style={styles.statusCard}><Text style={styles.kicker}>{booking.id}</Text><Text style={styles.status}>{statusLabels[booking.status]||booking.status}</Text><Text style={styles.service}>{booking.service} · {booking.preferred_date} {booking.preferred_time}</Text></View>
    <View style={styles.summary}><Row label={tr('name')} value={booking.customer_name}/><Row label={tr('pickup')} value={booking.pickup}/><Row label={tr('destination')} value={booking.destination}/><Row label="Photos" value={String(booking.photo_count||0)}/></View>
    <Text style={styles.sectionTitle}>{tr('modifyBooking')}</Text><Field label={tr('pickup')} value={pickup} onChangeText={setPickup}/><Field label={tr('destination')} value={destination} onChangeText={setDestination}/>
    <View style={styles.two}><TouchableOpacity style={[styles.field,{flex:1}]} onPress={()=>{setShowDate(!showDate);setShowTime(false)}}><Text style={styles.label}>{tr('date')}</Text><Text style={styles.pickerValue}>{date}</Text></TouchableOpacity><TouchableOpacity style={[styles.field,{flex:1}]} onPress={()=>{setShowTime(!showTime);setShowDate(false)}}><Text style={styles.label}>{tr('time')}</Text><Text style={styles.pickerValue}>{time}</Text></TouchableOpacity></View>
    {showDate&&<View style={styles.pickerShell}><DateTimePicker value={dt} mode="date" presentation={Platform.OS==='android'?'dialog':'inline'} onValueChange={(_,v)=>{if(v)setDate(dateString(v));if(Platform.OS==='android')setShowDate(false)}}/></View>}{showTime&&<View style={styles.pickerShell}><DateTimePicker value={dt} mode="time" presentation={Platform.OS==='android'?'dialog':'inline'} onValueChange={(_,v)=>{if(v)setTime(timeString(v));if(Platform.OS==='android')setShowTime(false)}}/></View>}
    <View style={styles.field}><Text style={styles.label}>{tr('notes')}</Text><TextInput multiline value={notes} onChangeText={setNotes} style={[styles.input,styles.textarea]}/></View>{!!message&&<Text style={styles.message}>{message}</Text>}
    <TouchableOpacity disabled={busy} onPress={modify} style={styles.primary}><Text style={styles.primaryText}>{tr('sendChange')}</Text></TouchableOpacity><TouchableOpacity disabled={busy} onPress={cancel} style={styles.danger}><Text style={styles.dangerText}>{tr('cancelBooking')}</Text></TouchableOpacity><TouchableOpacity onPress={()=>setBooking(null)} style={styles.secondary}><Text style={styles.secondaryText}>{tr('anotherBooking')}</Text></TouchableOpacity>
  </ScrollView>;
}
function Field(props:any){return <View style={styles.field}><Text style={styles.label}>{props.label}</Text><TextInput {...props} placeholderTextColor="#8A9895" style={styles.input}/></View>}
function Row({label,value}:{label:string;value:string}){return <View style={styles.row}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{value||'—'}</Text></View>}
const styles=StyleSheet.create({wrap:{padding:16,paddingBottom:40,gap:12},intro:{color:'#5F706D',fontSize:16,lineHeight:24},field:{backgroundColor:'#fff',borderRadius:radius.md,padding:14,borderWidth:1,borderColor:colors.line},label:{color:'#60706D',fontSize:11,fontWeight:'900',textTransform:'uppercase',letterSpacing:.7,marginBottom:7},input:{minHeight:38,color:colors.ink,fontSize:16,fontWeight:'650',padding:0},textarea:{minHeight:100,textAlignVertical:'top'},two:{flexDirection:'row',gap:10},pickerValue:{color:colors.ink,fontSize:16,fontWeight:'850',minHeight:38,textAlignVertical:'center'},pickerShell:{backgroundColor:'#fff',borderRadius:radius.lg,padding:8,borderWidth:1,borderColor:colors.line},primary:{minHeight:56,borderRadius:radius.md,backgroundColor:colors.lime,alignItems:'center',justifyContent:'center'},primaryText:{color:colors.ink,fontSize:16,fontWeight:'900'},secondary:{minHeight:50,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center'},secondaryText:{color:colors.ink,fontWeight:'850'},danger:{minHeight:50,borderRadius:radius.md,backgroundColor:'#F7E7E7',alignItems:'center',justifyContent:'center'},dangerText:{color:colors.danger,fontWeight:'900'},message:{color:colors.danger,fontSize:14},statusCard:{backgroundColor:colors.ink,borderRadius:radius.xl,padding:22},kicker:{color:colors.lime,fontSize:11,fontWeight:'900'},status:{color:'#fff',fontSize:30,fontWeight:'950',marginTop:7},service:{color:'#ABC0BC',fontSize:14,marginTop:7},summary:{backgroundColor:'#fff',borderRadius:radius.lg,borderWidth:1,borderColor:colors.line,overflow:'hidden'},row:{padding:14,borderBottomWidth:1,borderBottomColor:'#EDF0EC'},rowLabel:{color:colors.muted,fontSize:10,fontWeight:'900',textTransform:'uppercase'},rowValue:{color:colors.ink,fontSize:15,lineHeight:22,fontWeight:'700',marginTop:4},sectionTitle:{color:colors.ink,fontSize:20,fontWeight:'900',marginTop:7}});