import { useFocusEffect, router } from 'expo-router';
import { useCallback, useState } from 'react';
import { Alert, Linking, Platform, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Booking, getClientAccount, registerBookingPush } from '../../src/api';
import { localeOptions, useLanguage } from '../../src/i18n';
import { registerForNotifications } from '../../src/notifications';
import { SavedBookingCredential, secureStorage } from '../../src/storage';
import { colors, radius } from '../../src/theme';

const copy:any={
fi:{account:'Muuttobotti-tili',local:'Tällä laitteella',none:'Ei aktiivista varausta',logout:'Kirjaudu ulos',remove:'Poista',clear:'Poista paikalliset varaukset',pushOn:'Push-ilmoitukset ovat käytössä',pushOff:'Push-ilmoituksia ei ole vielä otettu käyttöön',version:'Muuttobotti Mobile v2.0.0',orders:'Omat tilaukset',noAccount:'Kirjaudu sähköpostilla etusivulta nähdäksesi kaikki tilauksesi.'},
en:{account:'Muuttobotti account',local:'On this device',none:'No active booking',logout:'Sign out',remove:'Remove',clear:'Clear local bookings',pushOn:'Push notifications are enabled',pushOff:'Push notifications are not enabled yet',version:'Muuttobotti Mobile v2.0.0',orders:'My orders',noAccount:'Sign in with email on the start screen to see all your orders.'},
ru:{account:'Аккаунт Muuttobotti',local:'На этом устройстве',none:'Нет активного заказа',logout:'Выйти',remove:'Удалить',clear:'Удалить локальные заказы',pushOn:'Push-уведомления включены',pushOff:'Push-уведомления ещё не включены',version:'Muuttobotti Mobile v2.0.0',orders:'Мои заказы',noAccount:'Войдите по email на стартовом экране, чтобы видеть все свои заказы.'},
uk:{account:'Акаунт Muuttobotti',local:'На цьому пристрої',none:'Немає активного замовлення',logout:'Вийти',remove:'Видалити',clear:'Видалити локальні замовлення',pushOn:'Push-сповіщення увімкнені',pushOff:'Push-сповіщення ще не увімкнені',version:'Muuttobotti Mobile v2.0.0',orders:'Мої замовлення',noAccount:'Увійдіть через email на стартовому екрані, щоб бачити всі замовлення.'}}

export default function ProfileScreen(){
 const {locale,setLocale,tr}=useLanguage();const t=copy[locale]||copy.fi;const[history,setHistory]=useState<SavedBookingCredential[]>([]);const[activeId,setActiveId]=useState('');const[pushEnabled,setPushEnabled]=useState(false);const[pushState,setPushState]=useState('');const[sessionEmail,setSessionEmail]=useState('');const[accountBookings,setAccountBookings]=useState<Booking[]>([]);
 const refresh=useCallback(async()=>{const[items,current,pushToken,session]=await Promise.all([secureStorage.getClientHistory(),secureStorage.getClientCredentials(),secureStorage.getPushToken(),secureStorage.getClientSession()]);setHistory(items);setActiveId(current.id);setPushEnabled(Boolean(pushToken));setSessionEmail(session.email);if(session.token){try{const account=await getClientAccount(session.token);setAccountBookings(account.bookings||[])}catch{setAccountBookings([])}}else setAccountBookings([])},[]);
 useFocusEffect(useCallback(()=>{void refresh()},[refresh]));
 const enablePush=async()=>{const result=await registerForNotifications();if(!result.ok){setPushState(tr('notificationUnavailable'));return}const current=await secureStorage.getClientCredentials();if(current.id&&current.key){try{await registerBookingPush(current.id,current.key,result.token,Platform.OS,locale)}catch{}}setPushState(tr('notificationReady'));await refresh()};
 const signOut=async()=>{await Promise.all([secureStorage.clearClientCredentials(),secureStorage.clearClientSession()]);router.replace('/')};
 const removeBooking=async(id:string)=>{await secureStorage.removeClientCredential(id);await refresh()};
 const clearBookings=()=>Alert.alert(t.clear,'',[{text:'Cancel',style:'cancel'},{text:t.clear,style:'destructive',onPress:async()=>{await secureStorage.clearClientHistory();await refresh()}}]);
 return <ScrollView contentContainerStyle={s.wrap}>
  <View style={s.hero}><View style={s.live}><Text style={s.liveText}>V2 · CLIENT HUB</Text></View><Text style={s.title}>{tr('profile')}</Text><Text style={s.copy}>{sessionEmail||tr('privacyCopy')}</Text></View>
  <View style={s.section}><Text style={s.sectionTitle}>{t.account}</Text>{sessionEmail?<><Text style={s.email}>{sessionEmail}</Text><Text style={s.small}>{accountBookings.length} {t.orders.toLowerCase()}</Text></>:<Text style={s.muted}>{t.noAccount}</Text>}<TouchableOpacity style={s.secondary} onPress={signOut}><Text style={s.secondaryText}>{t.logout}</Text></TouchableOpacity></View>
  {sessionEmail&&<View style={s.section}><Text style={s.sectionTitle}>{t.orders}</Text>{accountBookings.length===0?<Text style={s.muted}>—</Text>:accountBookings.map(item=><TouchableOpacity key={item.id} style={s.order} onPress={()=>router.push({pathname:'/track',params:{accountId:item.id}})}><View style={{flex:1}}><Text style={s.orderId}>{item.id}</Text><Text style={s.orderTitle}>{item.pickup} → {item.destination}</Text><Text style={s.orderMeta}>{item.preferred_date} {item.preferred_time} · {item.status}</Text></View>{Number(item.quoted_price||0)>0&&<Text style={s.price}>{Number(item.quoted_price).toFixed(0)} €</Text>}<Text style={s.arrow}>→</Text></TouchableOpacity>)}</View>}
  <View style={s.section}><Text style={s.sectionTitle}>{tr('language')}</Text><View style={s.langRow}>{localeOptions.map(item=><TouchableOpacity key={item.value} style={[s.lang,locale===item.value&&s.langActive]} onPress={()=>setLocale(item.value)}><Text style={[s.langText,locale===item.value&&s.langTextActive]}>{item.label}</Text></TouchableOpacity>)}</View></View>
  <View style={s.section}><Text style={s.sectionTitle}>{t.local}</Text><Text style={s.small}>{activeId||t.none}</Text>{history.map(item=><View key={item.id} style={s.localOrder}><TouchableOpacity style={s.localMain} onPress={()=>router.push({pathname:'/track',params:{id:item.id,key:item.key}})}><Text style={s.orderId}>{item.id}</Text><Text style={s.arrow}>→</Text></TouchableOpacity><TouchableOpacity style={s.remove} onPress={()=>removeBooking(item.id)}><Text style={s.removeText}>{t.remove}</Text></TouchableOpacity></View>)}{history.length>0&&<TouchableOpacity style={s.danger} onPress={clearBookings}><Text style={s.dangerText}>{t.clear}</Text></TouchableOpacity>}</View>
  <View style={s.section}><Text style={s.sectionTitle}>{tr('notifications')}</Text><Text style={s.muted}>{pushState||(pushEnabled?t.pushOn:t.pushOff)}</Text><TouchableOpacity style={s.primary} onPress={enablePush}><Text style={s.primaryText}>{tr('enableNotifications')}</Text></TouchableOpacity></View>
  <View style={s.section}><Text style={s.sectionTitle}>{tr('help')}</Text><TouchableOpacity style={s.action} onPress={()=>Linking.openURL('tel:+3584578767567')}><Text style={s.actionText}>045 787 67567</Text></TouchableOpacity><TouchableOpacity style={s.action} onPress={()=>Linking.openURL('https://wa.me/3584578767567')}><Text style={s.actionText}>WhatsApp</Text></TouchableOpacity><TouchableOpacity style={s.action} onPress={()=>Linking.openURL('mailto:autochemixfin@gmail.com')}><Text style={s.actionText}>autochemixfin@gmail.com</Text></TouchableOpacity></View>
  <Text style={s.version}>{t.version}</Text>
 </ScrollView>
}
const s=StyleSheet.create({wrap:{padding:16,paddingBottom:38,gap:12,backgroundColor:'#EEF3EE'},hero:{backgroundColor:'#06191F',borderRadius:radius.xl,padding:22},live:{alignSelf:'flex-start',backgroundColor:'#13353D',borderRadius:999,paddingHorizontal:9,paddingVertical:5},liveText:{color:'#C8FF36',fontSize:9,fontWeight:'950'},title:{color:'#fff',fontSize:34,fontWeight:'950',marginTop:8},copy:{color:'#A8BEB9',fontSize:13,lineHeight:20,marginTop:6},section:{backgroundColor:'#fff',borderRadius:radius.lg,padding:16,borderWidth:1,borderColor:colors.line,gap:9},sectionTitle:{color:colors.ink,fontSize:18,fontWeight:'950'},email:{color:colors.ink,fontSize:15,fontWeight:'850'},small:{color:'#667A75',fontSize:12},muted:{color:colors.muted,fontSize:13,lineHeight:20},order:{flexDirection:'row',alignItems:'center',gap:8,borderTopWidth:1,borderTopColor:'#EEF1EE',paddingVertical:11},orderId:{color:'#6E817C',fontSize:10,fontWeight:'950',letterSpacing:.7},orderTitle:{color:colors.ink,fontSize:13,fontWeight:'850',marginTop:3},orderMeta:{color:colors.muted,fontSize:10,marginTop:3},price:{color:colors.ink,fontWeight:'950',fontSize:13},arrow:{color:colors.ink,fontSize:19},langRow:{flexDirection:'row',gap:6},lang:{flex:1,minHeight:44,borderRadius:12,backgroundColor:'#EEF2ED',alignItems:'center',justifyContent:'center'},langActive:{backgroundColor:'#06191F'},langText:{color:'#667773',fontSize:12,fontWeight:'900'},langTextActive:{color:'#fff'},localOrder:{borderTopWidth:1,borderTopColor:'#EEF1EE',paddingTop:7},localMain:{flexDirection:'row',justifyContent:'space-between',paddingVertical:6},remove:{alignSelf:'flex-start',backgroundColor:'#F4F1EF',paddingHorizontal:9,paddingVertical:6,borderRadius:9},removeText:{color:colors.danger,fontSize:10,fontWeight:'900'},primary:{minHeight:50,borderRadius:13,backgroundColor:'#C8FF36',alignItems:'center',justifyContent:'center'},primaryText:{color:colors.ink,fontWeight:'950'},secondary:{minHeight:47,borderRadius:13,borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center'},secondaryText:{color:colors.ink,fontWeight:'900'},danger:{minHeight:43,borderRadius:12,backgroundColor:'#FFF0EF',alignItems:'center',justifyContent:'center'},dangerText:{color:colors.danger,fontSize:11,fontWeight:'900'},action:{minHeight:45,borderRadius:12,backgroundColor:'#F0F3EE',paddingHorizontal:13,justifyContent:'center'},actionText:{color:colors.ink,fontSize:13,fontWeight:'850'},version:{textAlign:'center',color:colors.muted,fontSize:10}})
