export type FaqLocale = "fi" | "en" | "uk" | "ru";

export const faqHeadings: Record<FaqLocale, { kicker: string; title: string; intro: string; booking: string; whatsapp: string }> = {
  fi: {
    kicker: "Usein kysytyt kysymykset",
    title: "Vastaukset ennen muuttopäivää.",
    intro: "Kokosimme yleisimmät kysymykset hinnasta, työajasta, autosta, pakkauksesta, siivouksesta ja varauksesta.",
    booking: "Varaa verkossa",
    whatsapp: "Kysy WhatsAppissa",
  },
  en: {
    kicker: "Frequently asked questions",
    title: "Answers before moving day.",
    intro: "The most common questions about pricing, billable time, the van, packing, cleaning and booking.",
    booking: "Book online",
    whatsapp: "Ask on WhatsApp",
  },
  uk: {
    kicker: "Часті запитання",
    title: "Відповіді до дня переїзду.",
    intro: "Найпоширеніші запитання про ціну, робочий час, автомобіль, пакування, прибирання та бронювання.",
    booking: "Забронювати",
    whatsapp: "Запитати у WhatsApp",
  },
  ru: {
    kicker: "Частые вопросы",
    title: "Ответы до дня переезда.",
    intro: "Самые частые вопросы о цене, рабочем времени, машине, упаковке, уборке и бронировании.",
    booking: "Забронировать",
    whatsapp: "Спросить в WhatsApp",
  },
};

export const faqContent: Record<FaqLocale, Array<[string, string]>> = {
  fi: [
    ["Miten muuton hinta määräytyy?", "Hinta riippuu muuttajien määrästä, työajasta, etäisyydestä, kohteen kulkureitistä ja mahdollisista lisäpalveluista. Laskuri antaa arvion ja lopullinen hinta vahvistetaan ennen työtä."],
    ["Onko muutossa minimiveloitusta?", "Useimmissa muuttopalveluissa minimiveloitus on kaksi tuntia. Mahdollinen poikkeus kerrotaan aina tarjouksessa ennen varausta."],
    ["Milloin maksettava työaika alkaa?", "Työaika alkaa, kun tiimi saapuu sovittuun nouto- tai palveluosoitteeseen."],
    ["Sisältyvätkö muuttoauto ja polttoaine hintaan?", "Vahvistetussa tarjouksessa kerrotaan aina selkeästi, mitä hintaan sisältyy. Muuttolaskurin lähtökohtana on palveluun kuuluva muuttoauto."],
    ["Voinko tilata yhden tai kaksi muuttajaa?", "Kyllä. Pieniin kuljetuksiin yksi muuttaja voi riittää, mutta isompaan muuttoon kaksi muuttajaa on yleensä nopeampi ja käytännöllisempi vaihtoehto."],
    ["Onnistuuko muutto tai kuljetus samalle päivälle?", "Kyllä, jos autolla ja tiimillä on vapaata kapasiteettia. Kiireellisessä tapauksessa kannattaa soittaa tai lähettää WhatsApp-viesti."],
    ["Voitteko auttaa pakkaamisessa?", "Kyllä. Pakkausapu voidaan lisätä varaukseen, ja laatikoista sekä muista pakkausmateriaaleista voidaan sopia erikseen."],
    ["Puraatteko ja kokoatteko huonekaluja?", "Kyllä. Tavallisten sänkyjen, pöytien, kaappien ja muiden kalusteiden purku sekä kokoaminen voidaan lisätä muuttoon."],
    ["Voitteko irrottaa ja kytkeä pesukoneen tai astianpesukoneen?", "Tavanomaiset irrotukset ja kytkennät voidaan hoitaa muuton yhteydessä, jos ne voidaan tehdä turvallisesti ilman erillisiä sähkö- tai putkitöitä."],
    ["Voiko muuttosiivouksen tilata samalla?", "Kyllä. Muutto ja muuttosiivous voidaan sopia samaan tilaukseen, jolloin aikataulu on helpompi pitää yhtenä kokonaisuutena."],
    ["Tuotteko siivousaineet ja välineet?", "Tavalliset ammattivälineet ja siivousaineet voidaan sisällyttää siivouspalveluun. Mahdolliset erikoistarpeet sovitaan etukäteen."],
    ["Voitteko viedä vanhat huonekalut tai tavarat pois?", "Kyllä. Nouto, lajittelu ja kuljetus kierrätys- tai Sortti-asemalle voidaan lisätä tilaukseen. Asemamaksut riippuvat tavaran määrästä ja laadusta."],
    ["Kuljetatteko pianoja tai muita erityisen raskaita tavaroita?", "Mahdollisesti. Ilmoita etukäteen paino, mitat, kerrokset, hissi ja kulkureitti, jotta voimme arvioida tarvittavan miehityksen ja kaluston turvallisesti."],
    ["Voinko lähettää kuvia tavaroista ennen muuttoa?", "Kyllä. Verkkovaraukseen voi liittää kuvia tavaroista, portaista, hissistä tai muista kulkureittiin vaikuttavista asioista."],
    ["Voinko muuttaa tai perua verkkovarauksen?", "Verkkovarauksesta saat yksityisen seurantalinkin, josta voit tarkistaa varauksen tiedot ja käytettävissä olevat itsepalvelutoiminnot. Tarvittaessa voit myös ottaa meihin suoraan yhteyttä."],
    ["Palveletteko vain Helsingissä?", "Emme. Palvelemme Helsingissä, Espoossa, Vantaalla, Tuusulassa ja muualla Uudellamaalla sekä sopimuksesta koko Suomessa."],
    ["Saanko kuitin tai laskun?", "Kyllä. Maksusta ja yritysasiakkaiden laskutuksesta voidaan sopia tilauksen vahvistamisen yhteydessä."],
    ["Miten saan mahdollisimman tarkan hinta-arvion?", "Anna nouto- ja kohdeosoite, asunnon koko, kerrokset ja hissit, tavaramäärä, mahdolliset raskaat esineet sekä kuvat. Mitä tarkemmat tiedot, sitä tarkempi arvio."],
  ],
  en: [
    ["How is the moving price calculated?", "The price depends on the number of movers, working time, distance, access conditions and selected extras. The calculator gives an estimate and the final price is confirmed before the job."],
    ["Is there a minimum charge?", "Most moving jobs have a two-hour minimum. Any exception is always stated in the quote before booking."],
    ["When does billable time start?", "Billable time starts when the team arrives at the agreed pickup or service address."],
    ["Are the van and fuel included?", "The confirmed quote always states clearly what is included. The moving calculator assumes a moving van is part of the service."],
    ["Can I book one or two movers?", "Yes. One mover may be enough for a small transport, while two movers are usually faster and more practical for a full move."],
    ["Can I book a same-day move or delivery?", "Yes, when the van and team have available capacity. For urgent work, call or send a WhatsApp message."],
    ["Can you help with packing?", "Yes. Packing help can be added to the booking, and boxes or other packing materials can be agreed separately."],
    ["Do you disassemble and assemble furniture?", "Yes. Beds, tables, cabinets and other standard furniture can be disassembled and reassembled as part of the move."],
    ["Can you disconnect and reconnect a washing machine or dishwasher?", "Standard disconnection and reconnection can be handled during the move when it can be done safely without separate electrical or plumbing work."],
    ["Can move-out cleaning be booked together with the move?", "Yes. Moving and move-out cleaning can be arranged in one booking so the schedule is easier to manage as one job."],
    ["Do you bring cleaning supplies and equipment?", "Standard professional equipment and cleaning products can be included. Any special requirements are agreed in advance."],
    ["Can you remove old furniture or unwanted items?", "Yes. Pickup, sorting and transport to a recycling or Sortti station can be added. Station fees depend on the amount and type of material."],
    ["Do you move pianos or other very heavy items?", "Possibly. Tell us the weight, dimensions, floors, elevator and access route in advance so we can assess the required team and equipment safely."],
    ["Can I send photos before the move?", "Yes. You can attach photos of the items, stairs, elevator or other access conditions to the online booking."],
    ["Can I change or cancel an online booking?", "Online bookings receive a private tracking link where you can review the booking and use available self-service options. You can also contact us directly."],
    ["Do you only work in Helsinki?", "No. We serve Helsinki, Espoo, Vantaa, Tuusula and the wider Uusimaa region, and by agreement all of Finland."],
    ["Can I get a receipt or invoice?", "Yes. Payment details and business invoicing can be agreed when the order is confirmed."],
    ["How do I get the most accurate estimate?", "Send both addresses, property size, floors and elevators, the approximate amount of belongings, any heavy items and photos. More detail means a better estimate."],
  ],
  uk: [
    ["Як формується ціна переїзду?", "Ціна залежить від кількості вантажників, робочого часу, відстані, умов доступу та додаткових послуг. Калькулятор дає орієнтир, а остаточну ціну ми підтверджуємо до початку роботи."],
    ["Чи є мінімальна оплата?", "Для більшості переїздів діє мінімум у дві години. Якщо є виняток, він завжди вказується у пропозиції до бронювання."],
    ["Коли починається оплачуваний час?", "Оплачуваний час починається, коли команда прибуває на погоджену адресу завантаження або надання послуги."],
    ["Чи входять автомобіль і пальне у ціну?", "У підтвердженій пропозиції завжди чітко зазначено, що входить у ціну. Калькулятор переїзду передбачає автомобіль як частину послуги."],
    ["Можна замовити одного або двох вантажників?", "Так. Для невеликого перевезення може вистачити одного вантажника, а для повного переїзду два зазвичай працюють швидше та зручніше."],
    ["Чи можна замовити переїзд або доставку в той самий день?", "Так, якщо автомобіль і команда вільні. Для термінового замовлення краще зателефонувати або написати у WhatsApp."],
    ["Ви допомагаєте з пакуванням?", "Так. Допомогу з пакуванням можна додати до бронювання, а коробки та інші матеріали узгодити окремо."],
    ["Ви розбираєте та збираєте меблі?", "Так. Ліжка, столи, шафи та інші стандартні меблі можна розібрати й зібрати під час переїзду."],
    ["Можете від'єднати та під'єднати пральну або посудомийну машину?", "Стандартне від'єднання та під'єднання можливе під час переїзду, якщо це безпечно і не потребує окремих електричних або сантехнічних робіт."],
    ["Чи можна разом замовити прибирання після переїзду?", "Так. Переїзд і фінальне прибирання можна оформити одним замовленням, щоб простіше узгодити весь графік."],
    ["Ви привозите засоби та інвентар для прибирання?", "Звичайний професійний інвентар і засоби можуть входити у послугу. Особливі вимоги узгоджуються заздалегідь."],
    ["Можете вивезти старі меблі або непотрібні речі?", "Так. Забір, сортування і доставка на станцію переробки або Sortti можна додати до замовлення. Плата станції залежить від кількості та виду речей."],
    ["Ви перевозите піаніно або інші дуже важкі речі?", "Можливо. Заздалегідь повідомте вагу, розміри, поверхи, наявність ліфта та маршрут, щоб ми безпечно оцінили потрібну команду й обладнання."],
    ["Можна надіслати фото речей до переїзду?", "Так. До онлайн-бронювання можна додати фото речей, сходів, ліфта або інших умов доступу."],
    ["Можна змінити або скасувати онлайн-бронювання?", "Після бронювання ви отримуєте приватне посилання, де можна переглянути замовлення та доступні функції самообслуговування. Також можна зв'язатися з нами напряму."],
    ["Ви працюєте лише в Гельсінкі?", "Ні. Ми працюємо у Гельсінкі, Еспоо, Вантаа, Туусула та по всій Уусімаа, а за домовленістю — по всій Фінляндії."],
    ["Чи можна отримати квитанцію або рахунок?", "Так. Оплату та виставлення рахунків для компаній можна узгодити під час підтвердження замовлення."],
    ["Як отримати найточнішу оцінку ціни?", "Надішліть обидві адреси, площу, поверхи й ліфти, приблизну кількість речей, важкі предмети та фото. Чим більше деталей, тим точніша оцінка."],
  ],
  ru: [
    ["Как формируется цена переезда?", "Цена зависит от количества грузчиков, рабочего времени, расстояния, условий доступа и дополнительных услуг. Калькулятор даёт ориентир, а итоговую цену мы подтверждаем до начала работы."],
    ["Есть ли минимальная оплата?", "Для большинства переездов действует минимум два часа. Если есть исключение, оно всегда указывается в предложении до бронирования."],
    ["Когда начинается оплачиваемое время?", "Оплачиваемое время начинается, когда команда приезжает на согласованный адрес загрузки или оказания услуги."],
    ["Входят ли машина и топливо в цену?", "В подтверждённом предложении всегда чётко указано, что входит в стоимость. Калькулятор переезда предполагает наличие машины в составе услуги."],
    ["Можно заказать одного или двух грузчиков?", "Да. Для небольшой перевозки может хватить одного грузчика, а для полноценного переезда два обычно работают быстрее и удобнее."],
    ["Можно заказать переезд или доставку в тот же день?", "Да, если машина и команда свободны. Для срочного заказа лучше позвонить или написать в WhatsApp."],
    ["Вы помогаете с упаковкой?", "Да. Помощь с упаковкой можно добавить к бронированию, а коробки и другие упаковочные материалы согласовать отдельно."],
    ["Вы разбираете и собираете мебель?", "Да. Кровати, столы, шкафы и другую обычную мебель можно разобрать и собрать в рамках переезда."],
    ["Можете отключить и подключить стиральную или посудомоечную машину?", "Стандартное отключение и подключение возможно во время переезда, если это безопасно и не требует отдельных электрических или сантехнических работ."],
    ["Можно вместе заказать уборку после переезда?", "Да. Переезд и финальную уборку можно оформить одним заказом, чтобы проще согласовать общий график."],
    ["Вы привозите средства и инвентарь для уборки?", "Обычный профессиональный инвентарь и средства могут входить в услугу. Особые требования согласовываются заранее."],
    ["Можете вывезти старую мебель или ненужные вещи?", "Да. Забор, сортировку и доставку на переработку или Sortti можно добавить к заказу. Плата станции зависит от количества и типа вещей."],
    ["Вы перевозите пианино или другие очень тяжёлые вещи?", "Возможно. Заранее сообщите вес, размеры, этажи, наличие лифта и маршрут, чтобы мы безопасно оценили нужную команду и оборудование."],
    ["Можно отправить фотографии вещей до переезда?", "Да. К онлайн-бронированию можно приложить фотографии вещей, лестниц, лифта или других условий доступа."],
    ["Можно изменить или отменить онлайн-бронирование?", "После бронирования вы получаете приватную ссылку, где можно проверить заказ и доступные функции самообслуживания. Также можно связаться с нами напрямую."],
    ["Вы работаете только в Хельсинки?", "Нет. Мы работаем в Хельсинки, Эспоо, Вантаа, Туусула и по всей Уусимаа, а по договорённости — по всей Финляндии."],
    ["Можно получить чек или счёт?", "Да. Оплату и выставление счетов для компаний можно согласовать при подтверждении заказа."],
    ["Как получить максимально точную оценку цены?", "Пришлите оба адреса, площадь, этажи и наличие лифтов, примерный объём вещей, тяжёлые предметы и фотографии. Чем больше деталей, тем точнее оценка."],
  ],
};
