"use client";
import { useRef, useState } from "react";
import { Sparkles } from "lucide-react";

type Locale = "fi" | "en" | "uk" | "ru";
type Item = {category:string; label:string; quantity:number|null; status:"included"|"excluded"|"uncertain"; evidence:string};
export type ReviewedInventory = {items:Item[]; volumeM3:number; heavy:boolean; load:"light"|"normal"|"full"; vehicle:"van"|"trailer"};
const volumes:Record<string,number>={sofa:1.8,bed:1.7,mattress:.8,washing_machine:.55,dishwasher:.5,fridge:.8,freezer:.7,wardrobe:1.2,dresser:.7,table:.65,chair:.25,armchair:.75,tv:.25,piano:1.5,safe:.5,bike:.7,box:.09};
const copy={
 fi:{title:"Kerro tavaroistasi — AI auttaa",intro:"Kirjoita muutettavat tavarat. Teksti lähetetään OpenAI-palveluun. Älä lisää nimiä, osoitteita tai yhteystietoja.",placeholder:"2 sohvaa, 10 laatikkoa ja pesukone. Piano ei tule mukaan.",go:"Tunnista tavarat",busy:"Tunnistetaan…",review:"Tarkista ja korjaa lista",qty:"Määrä",status:"Mukaan?",included:"Mukaan",excluded:"Ei mukaan",uncertain:"Epäselvä",confirm:"Tarkistin listan, määrät ja epäselvyydet.",apply:"Käytä laskurissa",applied:"Lisätty laskuriin",note:"Tilavuus on karkea arvio vakiokokoisista tavaroista. Käyttö päivittää tavaramäärän, ajoneuvon ja raskaat esineet; raskaille esineille valitaan 2 muuttajaa. Tarkista asunnon koko, kerrokset ja reitti itse.",blocked:"Täydennä määrät ja ratkaise epäselvät rivit. Tuntemattomat tavarat, piano, kassakaappi tai yli 20 m³ vaativat erillisen arvion.",error:"AI ei ole nyt käytettävissä. Voit käyttää laskuria käsin.",limit:"Pyyntöraja täyttyi. Yritä myöhemmin tai käytä laskuria käsin.",empty:"Tavaroita ei löytynyt. Tarkenna kuvausta."},
 en:{title:"Describe your things — AI can help",intro:"List the items you are moving. Your text is sent to OpenAI. Leave out names, addresses and contact details.",placeholder:"2 sofas, 10 boxes and a washing machine. No piano.",go:"Identify items",busy:"Identifying…",review:"Review and correct the list",qty:"Quantity",status:"Moving?",included:"Include",excluded:"Exclude",uncertain:"Unclear",confirm:"I checked the list, quantities and uncertainties.",apply:"Apply to calculator",applied:"Applied to calculator",note:"Volume is a rough estimate using standard item sizes. Apply updates load, vehicle and heavy items, selecting 2 movers for heavy items. Check home size, floors and route yourself.",blocked:"Fill in quantities and resolve unclear rows. Unknown items, pianos, safes or more than 20 m³ need a separate assessment.",error:"AI is unavailable right now. You can use the calculator manually.",limit:"Request limit reached. Try later or use the calculator manually.",empty:"No items found. Please add more detail."},
 ru:{title:"Опишите вещи — AI поможет",intro:"Перечислите вещи для переезда. Текст отправляется в OpenAI. Не указывайте имена, адреса и контакты.",placeholder:"2 дивана, 10 коробок и стиральная машина. Пианино не перевозим.",go:"Разобрать с AI",busy:"Разбираем…",review:"Проверьте и исправьте список",qty:"Количество",status:"Перевозим?",included:"Да",excluded:"Нет",uncertain:"Уточнить",confirm:"Я проверил список, количество и все неясности.",apply:"Применить к расчёту",applied:"Применено к расчёту",note:"Объём приблизительный, по типовым размерам вещей. Применение меняет загрузку, машину и отметку тяжёлых вещей; для тяжёлых вещей выбираются 2 грузчика. Площадь, этажи и маршрут проверьте вручную.",blocked:"Уточните количество и спорные строки. Неизвестные предметы, пианино, сейфы или объём свыше 20 м³ требуют отдельной оценки.",error:"AI сейчас недоступен. Калькулятор можно заполнить вручную.",limit:"Лимит запросов исчерпан. Попробуйте позже или заполните калькулятор вручную.",empty:"Вещи не найдены. Дополните описание."},
 uk:{title:"Опишіть речі — AI допоможе",intro:"Перелічіть речі для переїзду. Текст надсилається до OpenAI. Не вказуйте імена, адреси та контакти.",placeholder:"2 дивани, 10 коробок і пральна машина. Піаніно не перевозимо.",go:"Розібрати з AI",busy:"Опрацьовуємо…",review:"Перевірте та виправте список",qty:"Кількість",status:"Перевозимо?",included:"Так",excluded:"Ні",uncertain:"Уточнити",confirm:"Я перевірив список, кількість і всі неясності.",apply:"Застосувати до розрахунку",applied:"Застосовано",note:"Обʼєм приблизний, за типовими розмірами речей. Застосування змінює завантаження, машину й позначку важких речей; для важких речей обираються 2 вантажники. Площу, поверхи та маршрут перевірте вручну.",blocked:"Уточніть кількість і спірні рядки. Невідомі предмети, піаніно, сейфи або понад 20 м³ потребують окремої оцінки.",error:"AI зараз недоступний. Заповніть калькулятор вручну.",limit:"Ліміт запитів вичерпано. Спробуйте пізніше або заповніть калькулятор вручну.",empty:"Речі не знайдено. Доповніть опис."}
};
export default function HomeInventoryAssistant({locale,onApply}:{locale:Locale;onApply:(value:ReviewedInventory)=>void}){
 const t=copy[locale]; const [text,setText]=useState(""); const [items,setItems]=useState<Item[]|null>(null); const [uncertainties,setUncertainties]=useState<string[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [checked,setChecked]=useState(false); const [applied,setApplied]=useState(false); const lock=useRef(false);
 const included=items?.filter(i=>i.status==="included")??[];
 const volume=included.reduce((sum,i)=>sum+(volumes[i.category]??0)*(i.quantity??0),0);
 const blocked=!included.length||items?.some(i=>i.status==="uncertain"||(i.status==="included"&&(!i.quantity||!volumes[i.category]||["piano","safe"].includes(i.category))))||volume>20;
 async function analyse(){if(lock.current||!text.trim())return;lock.current=true;setBusy(true);setError("");setItems(null);setChecked(false);setApplied(false);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);
 try{const res=await fetch("/api/inventory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:text.trim()}),signal:controller.signal});if(!res.ok){setError(res.status===429?t.limit:t.error);return;}const data=await res.json();if(!data.ok||!Array.isArray(data.inventory?.items))throw Error("invalid response");setItems(data.inventory.items);setUncertainties(data.inventory.uncertainties??[]);if(!data.inventory.items.length)setError(t.empty);}catch{setError(t.error);}finally{clearTimeout(timer);lock.current=false;setBusy(false);}}
 function edit(index:number,patch:Partial<Item>){setItems(prev=>prev?.map((item,i)=>i===index?{...item,...patch}:item)??null);setChecked(false);setApplied(false);}
 return <section className="home-inventory" aria-labelledby="home-inventory-title">
 <style>{`.calculator-section .home-inventory{margin:14px 8px;padding:clamp(16px,3vw,26px);border-radius:22px;background:#102f34;color:#f4faf6;min-width:0}.home-inventory h3{display:flex;align-items:center;gap:10px;margin:0 0 10px;font-size:clamp(20px,3vw,26px);color:#fff}.home-inventory p{color:#ccdad6;font-size:14px;line-height:1.6;margin:10px 0}.home-inventory textarea{display:block;width:100%;box-sizing:border-box;min-height:94px;resize:vertical;padding:14px;border-radius:12px;border:1px solid #77938c;background:#f7fbf8;color:#102f34;font:inherit}.home-inventory button{padding:12px 18px;min-height:44px;border:0;border-radius:12px;background:#c8ff65;color:#102f34;font-weight:800;margin-top:12px;cursor:pointer}.home-inventory button:disabled{opacity:.5;cursor:default}.home-inventory .inventory-row{display:grid;grid-template-columns:minmax(0,1fr) 80px 125px;align-items:center;gap:10px;padding:12px 0;border-bottom:1px solid #45615a}.home-inventory .inventory-row span{overflow-wrap:anywhere}.home-inventory small{display:block;color:#bdcdc6;line-height:1.5}.home-inventory input[type=number],.home-inventory select{width:100%;min-height:42px;border-radius:8px;background:#f7fbf8;color:#102f34;border:1px solid #8baca0;padding:6px;font:inherit;box-sizing:border-box}.home-inventory .inventory-confirm{display:flex;align-items:flex-start;gap:10px;margin-top:16px;font-size:14px}.home-inventory input[type=checkbox]{width:20px;height:20px;flex-shrink:0}.home-inventory :focus-visible{outline:3px solid #c8ff65;outline-offset:3px}@media(max-width:480px){.home-inventory .inventory-row{grid-template-columns:minmax(0,1fr) 68px}.home-inventory .inventory-row select{grid-column:1/-1}.calculator-section .home-inventory{margin:10px 0}}`}</style>
 <h3 id="home-inventory-title"><Sparkles aria-hidden="true"/>{t.title}</h3><p id="inventory-disclosure">{t.intro}</p>
 <textarea aria-label={t.title} aria-describedby="inventory-disclosure" placeholder={t.placeholder} maxLength={4000} disabled={busy} value={text} onChange={e=>{setText(e.target.value);setItems(null);setChecked(false);setApplied(false);setError("");}}/>
 <button type="button" disabled={busy||!text.trim()} onClick={analyse}>{busy?t.busy:t.go}</button>
 {error&&<p role="alert">{error}</p>}
 {items&&items.length>0&&<div aria-live="polite"><h4>{t.review}</h4>{items.map((item,index)=><div className="inventory-row" key={index}><span>{item.label}<small>“{item.evidence}”</small></span><input aria-label={`${t.qty}: ${item.label}`} type="number" min={1} max={500} step={1} disabled={item.status==="excluded"} value={item.quantity??""} placeholder="?" onChange={e=>{const n=Number(e.target.value);edit(index,{quantity:Number.isInteger(n)&&n>=1&&n<=500?n:null});}}/><select aria-label={`${t.status}: ${item.label}`} value={item.status} onChange={e=>edit(index,{status:e.target.value as Item["status"]})}><option value="included">{t.included}</option><option value="excluded">{t.excluded}</option><option value="uncertain">{t.uncertain}</option></select></div>)}
 {uncertainties.length>0&&<ul>{uncertainties.map((u,i)=><li key={i}>{u}</li>)}</ul>}
 <p>{t.note}</p>{blocked?<p>{t.blocked}</p>:<p>≈ {volume.toFixed(1)} m³</p>}
 <label className="inventory-confirm"><input type="checkbox" checked={checked} onChange={e=>{setChecked(e.target.checked);setApplied(false);}}/>{t.confirm}</label>
 <button type="button" disabled={Boolean(blocked)||!checked||applied} onClick={()=>{const heavy=included.some(i=>["sofa","bed","wardrobe","washing_machine","dishwasher","fridge","freezer"].includes(i.category));onApply({items:items.map(i=>({...i})),volumeM3:Math.round(volume*10)/10,heavy,load:volume<7?"light":volume<14?"normal":"full",vehicle:volume<=13.5?"van":"trailer"});setApplied(true);}}>{applied?t.applied:t.apply}</button></div>}
 </section>;
}
