"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { AnimatePresence, motion } from "framer-motion";
import {
  ArrowRight, BarChart3, Bath, Bell, Boxes, Building2, CalendarDays, Camera,
  Check, CheckCircle2, ChevronDown, ChevronRight, CircleEuro, ClipboardCheck,
  Clock3, CreditCard, Hammer, Home, Languages, LayoutDashboard,
  MapPin, Menu, MessageCircle, Moon, Navigation, PackageCheck, Phone, Receipt,
  Recycle, Send, ShieldCheck, Sparkles, Star, Sun, Truck, UploadCloud,
  UserRound, UsersRound, X,
} from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import Image from "next/image";

type Locale = "fi" | "en" | "uk" | "ru";
type CalcMode = "moving" | "cleaning" | "transport";
type PortalMode = "customer" | "admin" | "employee";

const copy = {
  fi: { nav: ["Palvelut", "Hinnat", "Miten se toimii", "Arvostelut"], quote: "Pyydä tarjous", eyebrow: "Muutot · Kuljetukset · Siivous", titleA: "Kaikki hoituu.", titleB: "Yhdellä varauksella.", body: "Luotettava tiimi, iso pakettiauto ja läpinäkyvä hinta. Muutot, kuljetukset ja siivoukset kaikkialla Uudellamaalla — ja tarvittaessa koko Suomessa.", primary: "Laske hinta", secondary: "Varaa verkossa", rating: "4,9 / 5 asiakkaidemme arvio", response: "Vastaamme yleensä 5 minuutissa", trust: ["Vakuutettu palvelu", "Ei piilokuluja", "Samana päivänä"], stats: [["1 000+", "suoritettua työtä"], ["98 %", "tyytyväisiä asiakkaita"], ["24/7", "verkkovaraus"]], servicesKicker: "Kaikki kodin logistiikka", servicesTitle: "Yksi luotettava tiimi. Kaikki palvelut.", servicesBody: "Varaa vain se, mitä tarvitset — tai anna meidän hoitaa koko päivä alusta loppuun.", from: "alkaen", book: "Varaa palvelu" },
  en: { nav: ["Services", "Pricing", "How it works", "Reviews"], quote: "Get a quote", eyebrow: "Moving · Transport · Cleaning", titleA: "Consider it done.", titleB: "In one booking.", body: "A reliable team, a large van and transparent pricing. Moving, transport and cleaning across Uusimaa — and throughout Finland when you need us.", primary: "Calculate price", secondary: "Book online", rating: "4.9 / 5 customer rating", response: "We usually reply in 5 minutes", trust: ["Fully insured", "No hidden fees", "Same-day service"], stats: [["1,000+", "completed jobs"], ["98%", "customer satisfaction"], ["24/7", "online booking"]], servicesKicker: "Home logistics, simplified", servicesTitle: "One trusted team. Every service.", servicesBody: "Book exactly what you need — or let us manage the whole day from start to finish.", from: "from", book: "Book service" },
  uk: { nav: ["Послуги", "Ціни", "Як це працює", "Відгуки"], quote: "Отримати пропозицію", eyebrow: "Переїзди · Перевезення · Прибирання", titleA: "Усе буде зроблено.", titleB: "Одним бронюванням.", body: "Надійна команда, великий фургон і прозорі ціни. Переїзди, перевезення та прибирання по Уусімаа й усій Фінляндії.", primary: "Розрахувати ціну", secondary: "Забронювати", rating: "4,9 / 5 оцінка клієнтів", response: "Зазвичай відповідаємо за 5 хвилин", trust: ["Застраховано", "Без прихованих платежів", "У день замовлення"], stats: [["1 000+", "виконаних робіт"], ["98%", "задоволених клієнтів"], ["24/7", "онлайн-бронювання"]], servicesKicker: "Уся домашня логістика", servicesTitle: "Одна надійна команда. Усі послуги.", servicesBody: "Замовляйте саме те, що потрібно, або довірте нам увесь день від початку до кінця.", from: "від", book: "Замовити" },
  ru: { nav: ["Услуги", "Цены", "Как это работает", "Отзывы"], quote: "Получить расчёт", eyebrow: "Переезды · Перевозки · Уборка", titleA: "Всё будет сделано.", titleB: "Одним бронированием.", body: "Надёжная команда, большой фургон и прозрачные цены. Переезды, перевозки и уборка по Уусимаа и всей Финляндии.", primary: "Рассчитать цену", secondary: "Забронировать", rating: "4,9 / 5 оценка клиентов", response: "Обычно отвечаем за 5 минут", trust: ["Всё застраховано", "Без скрытых платежей", "В день заказа"], stats: [["1 000+", "выполненных работ"], ["98%", "довольных клиентов"], ["24/7", "онлайн-бронирование"]], servicesKicker: "Вся домашняя логистика", servicesTitle: "Одна надёжная команда. Все услуги.", servicesBody: "Закажите только нужное или доверьте нам весь день — от начала до конца.", from: "от", book: "Заказать" },
} as const;

const ui = {
  fi: { calcKicker: "Tiedä hinta etukäteen", calcTitle: "Laske hinta 60 sekunnissa.", calcText: "Saat reaaliaikaisen arvion. Lopullinen hinta vahvistetaan aina ennen varausta.", modes: ["Muutto", "Siivous", "Kuljetus"], homeType: "Kohde", apartment: "Asunto", house: "Omakotitalo", office: "Toimisto", size: "Koko", floor: "Kerros", elevator: "Hissi käytössä", packing: "Pakkausapua", afterClean: "Muuttosiivous", date: "Toivottu päivä", distance: "Etäisyys", windows: "Ikkunoita", cleanType: "Siivoustyyppi", regular: "Perussiivous", moveout: "Muuttosiivous", deep: "Suursiivous", weight: "Arvioitu paino", urgency: "Toimitus", normal: "Normaali", express: "Pikakuljetus", estimate: "Arvioitu hinta", duration: "Arvioitu kesto", vat: "Sis. ALV, auto ja polttoaineen", continue: "Jatka varaukseen", recommended: "Älykäs suositus", twoMovers: "Suosittelemme kahta muuttajaa ja isoa 13–15 m³ autoa.", processKicker: "Helppoa alusta loppuun", processTitle: "Valmista kolmella askeleella.", steps: [["Valitse palvelu", "Kerro osoitteet, määrä ja sopiva aika."], ["Saat vahvistuksen", "Näet hinnan ja tiimin tiedot ennen työtä."], ["Me hoidamme", "Seuraa tilausta ja maksa turvallisesti verkossa."]], portalKicker: "Yksi alusta kaikille", portalTitle: "Vähemmän viestejä. Enemmän hallintaa.", portals: ["Asiakas", "Hallinto", "Työntekijä"], reviewsKicker: "Asiakkaiden luottama", reviewsTitle: "Todellisia muuttoja. Todellisia arvioita.", faqKicker: "Hyvä tietää", faqTitle: "Usein kysytyt kysymykset", bookingKicker: "Varaa verkossa", bookingTitle: "Mihin voimme auttaa?", bookingText: "Täytä tiedot. Saat vahvistuksen sähköpostiin ja tekstiviestillä.", service: "Palvelu", name: "Nimi", phone: "Puhelin", email: "Sähköposti", pickup: "Nouto-osoite", destination: "Kohdeosoite", time: "Aika", notes: "Lisätiedot", photos: "Lisää kuvia", submit: "Lähetä varaus", success: "Varaus vastaanotettu!", successText: "Olemme sinuun pian yhteydessä hinnan ja ajan vahvistamiseksi.", contactTitle: "Palvelemme Uudellamaalla ja koko Suomessa.", contactText: "Kiireellinen kuljetus? Soita tai lähetä WhatsApp-viesti — vastaamme nopeasti.", cookies: "Käytämme välttämättömiä evästeitä ja luvallasi analytiikkaa palvelun parantamiseen.", accept: "Hyväksy kaikki", essential: "Vain välttämättömät", aiHello: "Hei! Olen Muuttobotti-assistentti. Mitä tarvitset?", aiOptions: ["Muuton hinta", "Vapaa aika", "Siivous"], aiReply: "Hyvä valinta. Laskurimme antaa heti arvion, tai voit jättää yhteystietosi varaukseen." },
  en: { calcKicker: "Know the price upfront", calcTitle: "Calculate your price in 60 seconds.", calcText: "Get a live estimate. We always confirm the final price before booking.", modes: ["Moving", "Cleaning", "Transport"], homeType: "Property", apartment: "Apartment", house: "House", office: "Office", size: "Size", floor: "Floor", elevator: "Elevator available", packing: "Packing help", afterClean: "Cleaning after move", date: "Preferred date", distance: "Distance", windows: "Windows", cleanType: "Cleaning type", regular: "Regular", moveout: "Move-out", deep: "Deep clean", weight: "Estimated weight", urgency: "Delivery", normal: "Normal", express: "Express", estimate: "Estimated price", duration: "Estimated duration", vat: "VAT, van and fuel included", continue: "Continue to booking", recommended: "Smart recommendation", twoMovers: "We recommend two movers and our large 13–15 m³ van.", processKicker: "Easy from start to finish", processTitle: "Done in three simple steps.", steps: [["Choose a service", "Tell us the addresses, volume and best time."], ["Get confirmation", "See your price and team details before the job."], ["We handle it", "Track the order and pay securely online."]], portalKicker: "One platform for everyone", portalTitle: "Fewer messages. More control.", portals: ["Customer", "Admin", "Employee"], reviewsKicker: "Trusted by customers", reviewsTitle: "Real moves. Real reviews.", faqKicker: "Good to know", faqTitle: "Frequently asked questions", bookingKicker: "Book online", bookingTitle: "How can we help?", bookingText: "Complete the details. Receive confirmation by email and SMS.", service: "Service", name: "Name", phone: "Phone", email: "Email", pickup: "Pickup address", destination: "Destination", time: "Time", notes: "Notes", photos: "Add photos", submit: "Send booking", success: "Booking received!", successText: "We will contact you shortly to confirm the price and time.", contactTitle: "Serving Uusimaa and all of Finland.", contactText: "Urgent delivery? Call or WhatsApp us — we respond quickly.", cookies: "We use essential cookies and, with permission, analytics to improve our service.", accept: "Accept all", essential: "Essential only", aiHello: "Hi! I’m the Muuttobotti assistant. What do you need?", aiOptions: ["Moving price", "Available time", "Cleaning"], aiReply: "Great choice. Our calculator gives an instant estimate, or you can leave your details in the booking form." },
  uk: { calcKicker: "Знайте ціну заздалегідь", calcTitle: "Розрахуйте ціну за 60 секунд.", calcText: "Отримайте миттєву оцінку. Остаточну ціну підтвердимо до бронювання.", modes: ["Переїзд", "Прибирання", "Перевезення"], homeType: "Об’єкт", apartment: "Квартира", house: "Будинок", office: "Офіс", size: "Площа", floor: "Поверх", elevator: "Є ліфт", packing: "Допомога з пакуванням", afterClean: "Прибирання після переїзду", date: "Бажана дата", distance: "Відстань", windows: "Вікна", cleanType: "Тип прибирання", regular: "Звичайне", moveout: "Після переїзду", deep: "Генеральне", weight: "Приблизна вага", urgency: "Доставка", normal: "Звичайна", express: "Експрес", estimate: "Орієнтовна ціна", duration: "Орієнтовний час", vat: "ПДВ, авто та паливо включено", continue: "Перейти до бронювання", recommended: "Розумна порада", twoMovers: "Рекомендуємо двох вантажників і великий фургон 13–15 м³.", processKicker: "Легко від початку до кінця", processTitle: "Три прості кроки.", steps: [["Оберіть послугу", "Вкажіть адреси, обсяг і зручний час."], ["Отримайте підтвердження", "Побачите ціну та дані команди до початку."], ["Ми все зробимо", "Стежте за замовленням і сплатіть онлайн."]], portalKicker: "Одна платформа для всіх", portalTitle: "Менше повідомлень. Більше контролю.", portals: ["Клієнт", "Адмін", "Працівник"], reviewsKicker: "Нам довіряють", reviewsTitle: "Реальні переїзди. Реальні відгуки.", faqKicker: "Корисно знати", faqTitle: "Поширені запитання", bookingKicker: "Онлайн-бронювання", bookingTitle: "Чим можемо допомогти?", bookingText: "Заповніть дані й отримайте підтвердження електронною поштою та SMS.", service: "Послуга", name: "Ім’я", phone: "Телефон", email: "Email", pickup: "Адреса завантаження", destination: "Адреса доставки", time: "Час", notes: "Примітки", photos: "Додати фото", submit: "Надіслати", success: "Бронювання отримано!", successText: "Скоро зв’яжемося для підтвердження ціни й часу.", contactTitle: "Працюємо в Уусімаа та по всій Фінляндії.", contactText: "Термінова доставка? Телефонуйте або пишіть у WhatsApp.", cookies: "Ми використовуємо необхідні cookie та, з дозволу, аналітику.", accept: "Прийняти все", essential: "Лише необхідні", aiHello: "Вітаю! Я асистент Muuttobotti. Що вам потрібно?", aiOptions: ["Ціна переїзду", "Вільний час", "Прибирання"], aiReply: "Чудовий вибір. Калькулятор одразу покаже оцінку, або залиште дані у формі." },
  ru: { calcKicker: "Знайте цену заранее", calcTitle: "Рассчитайте цену за 60 секунд.", calcText: "Получите мгновенную оценку. Итоговую цену подтвердим до бронирования.", modes: ["Переезд", "Уборка", "Перевозка"], homeType: "Объект", apartment: "Квартира", house: "Дом", office: "Офис", size: "Площадь", floor: "Этаж", elevator: "Есть лифт", packing: "Помощь с упаковкой", afterClean: "Уборка после переезда", date: "Желаемая дата", distance: "Расстояние", windows: "Количество окон", cleanType: "Тип уборки", regular: "Обычная", moveout: "После переезда", deep: "Генеральная", weight: "Примерный вес", urgency: "Доставка", normal: "Обычная", express: "Экспресс", estimate: "Примерная цена", duration: "Примерное время", vat: "НДС, машина и топливо включены", continue: "Перейти к бронированию", recommended: "Умная рекомендация", twoMovers: "Рекомендуем двух грузчиков и большой фургон 13–15 м³.", processKicker: "Легко от начала до конца", processTitle: "Три простых шага.", steps: [["Выберите услугу", "Укажите адреса, объём и удобное время."], ["Получите подтверждение", "Увидите цену и данные команды до начала."], ["Мы всё сделаем", "Отслеживайте заказ и оплачивайте онлайн."]], portalKicker: "Одна платформа для всех", portalTitle: "Меньше сообщений. Больше контроля.", portals: ["Клиент", "Админ", "Сотрудник"], reviewsKicker: "Нам доверяют", reviewsTitle: "Реальные переезды. Реальные отзывы.", faqKicker: "Полезно знать", faqTitle: "Частые вопросы", bookingKicker: "Онлайн-бронирование", bookingTitle: "Чем можем помочь?", bookingText: "Заполните данные и получите подтверждение по email и SMS.", service: "Услуга", name: "Имя", phone: "Телефон", email: "Email", pickup: "Адрес загрузки", destination: "Адрес доставки", time: "Время", notes: "Примечания", photos: "Добавить фото", submit: "Отправить", success: "Бронирование получено!", successText: "Скоро свяжемся для подтверждения цены и времени.", contactTitle: "Работаем по Уусимаа и всей Финляндии.", contactText: "Срочная доставка? Позвоните или напишите в WhatsApp.", cookies: "Мы используем необходимые cookie и, с разрешения, аналитику.", accept: "Принять все", essential: "Только необходимые", aiHello: "Привет! Я ассистент Muuttobotti. Что вам нужно?", aiOptions: ["Цена переезда", "Свободное время", "Уборка"], aiReply: "Отличный выбор. Калькулятор сразу даст оценку, или оставьте данные в форме." },
} as const;

const services = [
  { icon: Boxes, key: "moving", title: { fi: "Muuttopalvelu", en: "Moving", uk: "Переїзди", ru: "Переезды" }, desc: { fi: "Koti- ja yritysmuutot, pakkaus sekä kalusteiden purku.", en: "Home and office moves, packing and furniture disassembly.", uk: "Переїзди дому й офісу, пакування та розбирання меблів.", ru: "Переезды дома и офиса, упаковка и разборка мебели." }, price: "59 € / h", tone: "mint" },
  { icon: Truck, key: "transport", title: { fi: "Kuljetukset", en: "Transport", uk: "Перевезення", ru: "Перевозки" }, desc: { fi: "Huonekalut, kodinkoneet, noudot ja pikakuljetukset.", en: "Furniture, appliances, store pickups and express delivery.", uk: "Меблі, техніка, забір із магазину та експрес-доставка.", ru: "Мебель, техника, забор из магазина и экспресс-доставка." }, price: "49 € / h", tone: "blue" },
  { icon: Sparkles, key: "cleaning", title: { fi: "Siivous", en: "Cleaning", uk: "Прибирання", ru: "Уборка" }, desc: { fi: "Muuttosiivous, kotisiivous ja toimistosiivous takuulla.", en: "Move-out, home and office cleaning with a quality guarantee.", uk: "Прибирання після переїзду, дому та офісу з гарантією.", ru: "Уборка после переезда, дома и офиса с гарантией." }, price: "32,90 € / h", tone: "sand" },
  { icon: Building2, key: "windows", title: { fi: "Ikkunanpesu", en: "Window cleaning", uk: "Миття вікон", ru: "Мойка окон" }, desc: { fi: "Raidattomat ikkunat, karmit ja parvekelasit ammattivälineillä.", en: "Streak-free windows, frames and balcony glass.", uk: "Вікна без розводів, рами та балконне скло.", ru: "Окна без разводов, рамы и балконное остекление." }, price: "45 €", tone: "ice" },
  { icon: Hammer, key: "assembly", title: { fi: "Kalusteasennus", en: "Furniture assembly", uk: "Збирання меблів", ru: "Сборка мебели" }, desc: { fi: "IKEA- ja muiden kalusteiden kokoaminen turvallisesti.", en: "Safe assembly of IKEA and other furniture.", uk: "Безпечне збирання IKEA та інших меблів.", ru: "Безопасная сборка IKEA и другой мебели." }, price: "45 € / h", tone: "lavender" },
  { icon: Recycle, key: "junk", title: { fi: "Kierrätys & poisvienti", en: "Junk removal", uk: "Вивіз речей", ru: "Вывоз вещей" }, desc: { fi: "Nouto, lajittelu ja vastuullinen kuljetus Sortti-asemalle.", en: "Pickup, sorting and responsible recycling-station transport.", uk: "Забір, сортування та доставка на станцію переробки.", ru: "Забор, сортировка и доставка на станцию переработки." }, price: "60 €", tone: "peach" },
] as const;

const faqs: Record<Locale, [string, string][]> = {
  fi: [["Miten hinta lasketaan?", "Hinta perustuu tiimin kokoon, aikaan, etäisyyteen ja valittuihin lisäpalveluihin."], ["Onko minimiveloitusta?", "Useimmissa muuttopalveluissa minimiveloitus on kaksi tuntia."], ["Milloin työaika alkaa?", "Työaika alkaa, kun saavumme sovittuun nouto-osoitteeseen."], ["Sisältyykö polttoaine hintaan?", "Laskurin vahvistetussa tarjouksessa ilmoitetaan aina selkeästi, mitä hinta sisältää."], ["Ovatko tavarani vakuutettuja?", "Kyllä, toimimme vastuullisesti ja palvelulla on asianmukainen vastuuvakuutus."], ["Voinko varata samalle päivälle?", "Kyllä, vapaan kapasiteetin mukaan."], ["Kuljetatteko pianoja?", "Kyllä, kun paino, mitat ja kulkureitti ilmoitetaan etukäteen."], ["Voitteko pakata tavarani?", "Kyllä. Tuomme tarvittaessa myös laatikot ja pakkausmateriaalit."], ["Purkaako tiimi huonekalut?", "Kyllä, purku ja kokoaminen voidaan lisätä varaukseen."], ["Kytkettekö kodinkoneet?", "Tavanomaiset irrotukset ja kytkennät voidaan sopia varauksen yhteydessä."], ["Mitä muuttosiivous sisältää?", "Keittiön, kylpyhuoneen, pintojen ja lattioiden perusteellisen siivouksen sovitun listan mukaan."], ["Onko siivouksella takuu?", "Kyllä, korjaamme mahdolliset puutteet sovitun tarkastusajan puitteissa."], ["Tuotteko siivousaineet?", "Kyllä, ammattivälineet ja tavalliset aineet sisältyvät palveluun."], ["Pesettekö parvekelasit?", "Kyllä, ne voidaan lisätä ikkunanpesuun."], ["Viekö tiimi roskat?", "Kyllä, kuljetamme lajitellut tavarat kierrätysasemalle; asemamaksut vahvistetaan etukäteen."], ["Saanko kuitin ja laskun?", "Kyllä, saat sähköisen kuitin ja laskun asiakasnäkymään."], ["Miten maksan?", "Kortti- ja verkkopankkimaksut voidaan maksaa turvallisesti vahvistuksen jälkeen."], ["Voinko muuttaa varausta?", "Kyllä, ajankohtaa ja tietoja voi muuttaa asiakasnäkymästä tai ottamalla yhteyttä."], ["Voinko peruuttaa varauksen?", "Kyllä. Mahdollinen peruutusmaksu riippuu siitä, kuinka lähellä työaikaa peruutus tehdään."], ["Palveletteko Helsingin ulkopuolella?", "Kyllä, palvelemme Uudellamaalla ja sopimuksesta koko Suomessa."], ["Saanko yritysasiakkaana laskun?", "Kyllä, tarjoamme yrityksille laskutuksen ja säännölliset kuljetussopimukset."]],
  en: [["How is the price calculated?", "It is based on team size, time, distance and selected extras."], ["Is there a minimum charge?", "Most moving services have a two-hour minimum."], ["When does billable time start?", "It starts when we arrive at the agreed pickup address."], ["Is fuel included?", "Every confirmed quote clearly states what is included."], ["Are my belongings insured?", "Yes, our service carries appropriate liability cover."], ["Can I book the same day?", "Yes, subject to available capacity."], ["Do you move pianos?", "Yes, when weight, dimensions and access are provided in advance."], ["Can you pack for me?", "Yes, and we can supply boxes and packing materials."], ["Do you disassemble furniture?", "Yes, disassembly and assembly can be added."], ["Do you connect appliances?", "Standard disconnection and connection can be agreed when booking."], ["What is included in move-out cleaning?", "A thorough clean of kitchen, bathroom, surfaces and floors to an agreed checklist."], ["Is cleaning guaranteed?", "Yes, we correct agreed deficiencies within the inspection period."], ["Do you bring cleaning products?", "Yes, professional equipment and standard products are included."], ["Do you clean balcony glass?", "Yes, it can be added to window cleaning."], ["Can you remove junk?", "Yes, we sort and transport items to a recycling station; fees are confirmed first."], ["Will I receive a receipt?", "Yes, digital receipts and invoices appear in the customer view."], ["How can I pay?", "Secure card and online payments are available after confirmation."], ["Can I modify a booking?", "Yes, in the customer view or by contacting us."], ["Can I cancel?", "Yes. Any fee depends on how close the cancellation is to the job."], ["Do you work outside Helsinki?", "Yes, across Uusimaa and by agreement throughout Finland."], ["Do business customers get invoicing?", "Yes, we offer invoicing and recurring transport agreements."]],
  uk: [], ru: [],
};
faqs.uk = faqs.en.map(([q, a]) => [q, a]);
faqs.ru = faqs.en.map(([q, a]) => [q, a]);

const flags: Record<Locale, string> = { fi: "FI", en: "EN", uk: "UA", ru: "RU" };

export default function MuuttobottiApp() {
  const [locale, setLocale] = useState<Locale>("fi");
  const [menuOpen, setMenuOpen] = useState(false);
  const [langOpen, setLangOpen] = useState(false);
  const [theme, setTheme] = useState<"light" | "dark">("light");
  const [calcMode, setCalcMode] = useState<CalcMode>("moving");
  const [portal, setPortal] = useState<PortalMode>("customer");
  const [size, setSize] = useState(55);
  const [floor, setFloor] = useState(2);
  const [distance, setDistance] = useState(18);
  const [windows, setWindows] = useState(6);
  const [weight, setWeight] = useState(80);
  const [elevator, setElevator] = useState(true);
  const [packing, setPacking] = useState(false);
  const [afterClean, setAfterClean] = useState(false);
  const [express, setExpress] = useState(false);
  const [cleanType, setCleanType] = useState("regular");
  const [faqOpen, setFaqOpen] = useState<number | null>(0);
  const [cookie, setCookie] = useState<boolean | null>(null);
  const [chatOpen, setChatOpen] = useState(false);
  const [chatReply, setChatReply] = useState(false);
  const [bookingState, setBookingState] = useState<"idle" | "sending" | "done" | "error">("idle");
  const c = copy[locale];
  const u = ui[locale];

  useEffect(() => {
    const saved = window.localStorage.getItem("muuttobotti-cookie"); if (saved) window.setTimeout(() => setCookie(true), 0);
    if ("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(() => undefined);
  }, []);

  const estimate = useMemo(() => {
    if (calcMode === "moving") {
      const hours = Math.max(2, 1.4 + size / 28 + Math.max(0, floor - (elevator ? 2 : 0)) * .22 + (packing ? 1.5 : 0));
      return { price: Math.round(hours * 75 + distance * .65 + (afterClean ? size * 1.1 : 0)), hours: `${hours.toFixed(1)}–${(hours + .8).toFixed(1)} h` };
    }
    if (calcMode === "cleaning") {
      const multiplier = cleanType === "deep" ? 1.45 : cleanType === "moveout" ? 1.25 : 1;
      const hours = Math.max(2, size / 24 * multiplier + windows * .12);
      return { price: Math.round(hours * 32.9), hours: `${hours.toFixed(1)}–${(hours + .7).toFixed(1)} h` };
    }
    const hours = Math.max(1, 1 + distance / 48 + weight / 500);
    return { price: Math.round(42 + distance * 1.05 + weight * .05 + (express ? 35 : 0)), hours: `${hours.toFixed(1)}–${(hours + .5).toFixed(1)} h` };
  }, [calcMode, size, floor, distance, windows, elevator, packing, afterClean, express, cleanType, weight]);

  const scrollTo = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); setMenuOpen(false); };
  const acceptCookies = (value: string) => { window.localStorage.setItem("muuttobotti-cookie", value); setCookie(true); };
  async function submitBooking(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBookingState("sending");
    try {
      const response = await fetch("/api/bookings", { method: "POST", body: new FormData(event.currentTarget) });
      if (!response.ok) throw new Error("booking failed");
      setBookingState("done"); event.currentTarget.reset();
    } catch { setBookingState("error"); }
  }

  return (
    <main className={`site-shell ${theme === "dark" ? "dark-theme" : ""}`}>
      <header className="topbar">
        <button className="brand" onClick={() => scrollTo("home")} aria-label="Muuttobotti home"><span className="brand-mark"><PackageCheck size={22} strokeWidth={2.4} /></span><span>muutto<span>botti</span></span></button>
        <nav className="desktop-nav" aria-label="Primary navigation">{c.nav.map((item, i) => <button key={item} onClick={() => scrollTo(["services", "calculator", "process", "reviews"][i])}>{item}</button>)}</nav>
        <div className="header-actions">
          <button className="theme-button" onClick={() => setTheme(theme === "light" ? "dark" : "light")} aria-label="Toggle dark mode">{theme === "light" ? <Moon size={17}/> : <Sun size={17}/>}</button>
          <div className="language-wrap"><button className="lang-button" onClick={() => setLangOpen(!langOpen)} aria-expanded={langOpen}><Languages size={17} /> {flags[locale]} <ChevronDown size={14} /></button><AnimatePresence>{langOpen && <motion.div className="lang-menu" initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}>{(["fi", "en", "uk", "ru"] as Locale[]).map((lang) => <button key={lang} onClick={() => { setLocale(lang); setLangOpen(false); }} className={locale === lang ? "active" : ""}>{flags[lang]} <Check size={14} /></button>)}</motion.div>}</AnimatePresence></div>
          <button className="quote-button" onClick={() => scrollTo("calculator")}>{c.quote} <ArrowRight size={17} /></button>
          <button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Open menu">{menuOpen ? <X /> : <Menu />}</button>
        </div>
        <AnimatePresence>{menuOpen && <motion.nav className="mobile-nav" initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} exit={{ opacity: 0, height: 0 }}>{c.nav.map((item, i) => <button key={item} onClick={() => scrollTo(["services", "calculator", "process", "reviews"][i])}>{item}</button>)}</motion.nav>}</AnimatePresence>
      </header>

      <section className="hero" id="home">
        <Image className="hero-media" src="/muuttobotti-hero.png" alt="Muuttobotti movers loading a large moving van at a Finnish apartment building" fill priority unoptimized sizes="100vw" />
        <div className="hero-noise"/><div className="hero-glow"/>
        <motion.div className="hero-copy" initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .65 }}>
          <div className="eyebrow"><span/> {c.eyebrow}</div><h1>{c.titleA}<br/><em>{c.titleB}</em></h1><p>{c.body}</p>
          <div className="hero-actions"><button className="primary-button" onClick={() => scrollTo("calculator")}>{c.primary} <ArrowRight size={19}/></button><button className="secondary-button" onClick={() => scrollTo("booking")}>{c.secondary}</button></div>
          <div className="rating-row"><div className="avatars"><span>SK</span><span>MA</span><span>JL</span></div><div><div className="stars">★★★★★</div><small>{c.rating}</small></div></div>
        </motion.div>
        <div className="availability-pill"><span className="live-dot"/> {c.response}</div>
        <div className="trust-strip">{c.trust.map((item, i) => <div key={item}>{i === 0 ? <ShieldCheck/> : i === 1 ? <Check/> : <Clock3/>}<span>{item}</span></div>)}</div>
      </section>

      <section className="stats-band" aria-label="Company statistics">{c.stats.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}<div className="cities"><span>HELSINKI</span><span>ESPOO</span><span>VANTAA</span><span>TUUSULA</span></div></section>

      <section className="services-section" id="services">
        <div className="section-heading"><div><span className="kicker">{c.servicesKicker}</span><h2>{c.servicesTitle}</h2></div><p>{c.servicesBody}</p></div>
        <div className="service-grid">{services.map((service, i) => { const Icon = service.icon; return <motion.article className={`service-card ${service.tone}`} key={service.key} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .06 }}><div className="service-icon"><Icon size={25}/></div><h3>{service.title[locale]}</h3><p>{service.desc[locale]}</p><div className="service-price"><span>{c.from}</span><strong>{service.price}</strong></div><button onClick={() => scrollTo("calculator")}>{c.book}<ArrowRight size={16}/></button></motion.article> })}</div>
      </section>

      <section className="calculator-section" id="calculator">
        <div className="calculator-intro"><span className="kicker light">{u.calcKicker}</span><h2>{u.calcTitle}</h2><p>{u.calcText}</p><div className="smart-note"><Sparkles size={18}/><div><strong>{u.recommended}</strong><span>{u.twoMovers}</span></div></div></div>
        <div className="calculator-card">
          <div className="calc-tabs">{(["moving", "cleaning", "transport"] as CalcMode[]).map((mode, i) => <button key={mode} className={calcMode === mode ? "active" : ""} onClick={() => setCalcMode(mode)}>{i === 0 ? <Boxes/> : i === 1 ? <Sparkles/> : <Truck/>}{u.modes[i]}</button>)}</div>
          <div className="calc-fields">
            {calcMode === "moving" && <><label>{u.homeType}<select><option>{u.apartment}</option><option>{u.house}</option><option>{u.office}</option></select></label><label>{u.size}<div className="range-value">{size} m²</div><input type="range" min="15" max="220" value={size} onChange={e => setSize(+e.target.value)}/></label><label>{u.floor}<div className="range-value">{floor}</div><input type="range" min="0" max="12" value={floor} onChange={e => setFloor(+e.target.value)}/></label><label>{u.distance}<div className="range-value">{distance} km</div><input type="range" min="1" max="500" value={distance} onChange={e => setDistance(+e.target.value)}/></label><div className="switch-grid"><button className={elevator ? "on" : ""} onClick={() => setElevator(!elevator)}><CheckCircle2/>{u.elevator}</button><button className={packing ? "on" : ""} onClick={() => setPacking(!packing)}><Boxes/>{u.packing}</button><button className={afterClean ? "on" : ""} onClick={() => setAfterClean(!afterClean)}><Sparkles/>{u.afterClean}</button></div></>}
            {calcMode === "cleaning" && <><label>{u.size}<div className="range-value">{size} m²</div><input type="range" min="20" max="300" value={size} onChange={e => setSize(+e.target.value)}/></label><label>{u.windows}<div className="range-value">{windows}</div><input type="range" min="0" max="30" value={windows} onChange={e => setWindows(+e.target.value)}/></label><label>{u.cleanType}<select value={cleanType} onChange={e => setCleanType(e.target.value)}><option value="regular">{u.regular}</option><option value="moveout">{u.moveout}</option><option value="deep">{u.deep}</option></select></label><div className="feature-list"><span><Bath/> Bathroom & sauna</span><span><Sparkles/> Professional supplies</span><span><ShieldCheck/> Quality guarantee</span></div></>}
            {calcMode === "transport" && <><label>{u.distance}<div className="range-value">{distance} km</div><input type="range" min="1" max="600" value={distance} onChange={e => setDistance(+e.target.value)}/></label><label>{u.weight}<div className="range-value">{weight} kg</div><input type="range" min="5" max="1200" step="5" value={weight} onChange={e => setWeight(+e.target.value)}/></label><label>{u.urgency}<select value={express ? "express" : "normal"} onChange={e => setExpress(e.target.value === "express")}><option value="normal">{u.normal}</option><option value="express">{u.express}</option></select></label><div className="route-preview"><MapPin/><span>Helsinki</span><div/><Navigation/><span>Espoo</span></div></>}
          </div>
          <div className="estimate-box"><div><span>{u.estimate}</span><strong>{estimate.price} €</strong><small>{u.vat}</small></div><div><span>{u.duration}</span><strong className="time-estimate">{estimate.hours}</strong></div><button onClick={() => scrollTo("booking")}>{u.continue}<ArrowRight/></button></div>
        </div>
      </section>

      <section className="process-section" id="process"><div className="center-heading"><span className="kicker">{u.processKicker}</span><h2>{u.processTitle}</h2></div><div className="steps-grid">{u.steps.map(([title, text], i) => <motion.article key={title} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><span>0{i + 1}</span><div className="step-icon">{i === 0 ? <CalendarDays/> : i === 1 ? <Bell/> : <Truck/>}</div><h3>{title}</h3><p>{text}</p></motion.article>)}</div></section>

      <section className="portal-section">
        <div className="portal-heading"><span className="kicker light">{u.portalKicker}</span><h2>{u.portalTitle}</h2><div className="portal-tabs">{(["customer", "admin", "employee"] as PortalMode[]).map((mode, i) => <button key={mode} className={portal === mode ? "active" : ""} onClick={() => setPortal(mode)}>{u.portals[i]}</button>)}</div></div>
        <div className="dashboard-mockup">
          <aside><div className="mini-brand"><PackageCheck/> M</div>{[LayoutDashboard, CalendarDays, Receipt, MessageCircle, UserRound].map((Icon, i) => <span key={i} className={i === 0 ? "active" : ""}><Icon/></span>)}</aside>
          <div className="dashboard-main"><div className="dash-top"><div><small>{portal === "admin" ? "Operations overview" : portal === "employee" ? "Wednesday, 5 August" : "Welcome back, Anna"}</small><h3>{portal === "admin" ? "Business dashboard" : portal === "employee" ? "Today’s schedule" : "Your bookings"}</h3></div><div className="dash-avatar">AK</div></div>
            {portal === "customer" && <div className="booking-track"><div className="track-head"><div><span>MB-2048</span><h4>Apartment move · Helsinki → Espoo</h4></div><b>Confirmed</b></div><div className="tracking-line"><span className="done"><Check/></span><i/><span className="done"><Truck/></span><i/><span><Home/></span></div><div className="tracking-labels"><span>Booked</span><span>Team arriving 09:00</span><span>Completed</span></div><div className="dash-cards"><div><CreditCard/><span>Estimate</span><strong>225 €</strong></div><div><CalendarDays/><span>Date</span><strong>08 Aug</strong></div><div><UsersRound/><span>Team</span><strong>2 movers</strong></div></div></div>}
            {portal === "admin" && <><div className="dash-cards admin"><div><CircleEuro/><span>Revenue</span><strong>12 480 €</strong><small>+18.4%</small></div><div><ClipboardCheck/><span>Orders</span><strong>68</strong><small>12 today</small></div><div><UsersRound/><span>Customers</span><strong>213</strong><small>+24</small></div></div><div className="admin-row"><div className="chart"><BarChart3/><div><span style={{height:"38%"}}/><span style={{height:"55%"}}/><span style={{height:"44%"}}/><span style={{height:"82%"}}/><span style={{height:"66%"}}/><span style={{height:"90%"}}/></div></div><div className="next-orders"><strong>Next orders</strong><span><i/>09:00 Helsinki · Moving</span><span><i/>12:30 Espoo · Cleaning</span><span><i/>15:00 Vantaa · Delivery</span></div></div></>}
            {portal === "employee" && <div className="job-card"><div className="job-time">09:00<strong>01</strong></div><div><span>APARTMENT MOVE</span><h4>Ruoholahti → Tapiola</h4><p><MapPin/> 18 km · 2 movers · Crafter 15 m³</p><div className="job-actions"><button><Navigation/> Navigate</button><button><Camera/> Upload photos</button><button><ClipboardCheck/> Complete job</button></div></div></div>}
          </div>
        </div>
      </section>

      <section className="reviews-section" id="reviews"><div className="section-heading"><div><span className="kicker">{u.reviewsKicker}</span><h2>{u.reviewsTitle}</h2></div><div className="google-rating"><span className="google-g">G</span><strong>4.9</strong><div><span>★★★★★</span><small>Google Reviews</small></div></div></div><div className="reviews-grid">{[["Anna K.", "Espoo", "Excellent service from start to finish. The team was careful, quick and genuinely friendly."], ["Mikko P.", "Helsinki", "Transparent price and no surprises. Our entire apartment was moved faster than expected."], ["Olena S.", "Vantaa", "Замечательная команда. Всё аккуратно упаковали, перевезли и собрали на новом месте."]].map(([name, city, text], i) => <article key={name}><div className="review-top"><div className="review-avatar">{name.slice(0,1)}</div><div><strong>{name}</strong><span><CheckCircle2/> Verified · {city}</span></div><div className="stars">★★★★★</div></div><p>“{text}”</p><small>{i + 2} weeks ago</small></article>)}</div></section>

      <section className="booking-section" id="booking"><div className="booking-copy"><span className="kicker light">{u.bookingKicker}</span><h2>{u.bookingTitle}</h2><p>{u.bookingText}</p><div className="booking-benefits"><span><CheckCircle2/> Instant request confirmation</span><span><CheckCircle2/> Modify or cancel online</span><span><CheckCircle2/> Secure payment and receipt</span></div></div><form className="booking-form" onSubmit={submitBooking}><input type="text" name="website" className="honeypot" tabIndex={-1} autoComplete="off"/><label>{u.service}<select name="service" required>{services.map(service => <option key={service.key} value={service.key}>{service.title[locale]}</option>)}</select></label><div className="form-row"><label>{u.name}<input name="name" required autoComplete="name" placeholder="Anna Korhonen"/></label><label>{u.phone}<input name="phone" required autoComplete="tel" placeholder="+358 40 123 4567"/></label></div><label>{u.email}<input name="email" type="email" required autoComplete="email" placeholder="anna@example.fi"/></label><div className="form-row"><label>{u.pickup}<input name="pickup" required placeholder="Mannerheimintie 1, Helsinki"/></label><label>{u.destination}<input name="destination" required placeholder="Tapiolantie 4, Espoo"/></label></div><div className="form-row"><label>{u.date}<input name="date" type="date" required/></label><label>{u.time}<input name="time" type="time" required/></label></div><label>{u.notes}<textarea name="notes" rows={3} placeholder="Sofa, washing machine, 20 boxes…"/></label><label className="upload-field"><UploadCloud/><span>{u.photos}<small>JPG, PNG or WebP · max 8 MB</small></span><input name="photos" type="file" accept="image/png,image/jpeg,image/webp" multiple/></label><button className="submit-button" disabled={bookingState === "sending"}>{bookingState === "sending" ? "…" : u.submit}<Send/></button>{bookingState === "error" && <p className="form-error">Could not send. Please call or WhatsApp us.</p>}</form></section>

      <section className="faq-section"><div className="faq-title"><span className="kicker">{u.faqKicker}</span><h2>{u.faqTitle}</h2><p>Still need help? <button onClick={() => setChatOpen(true)}>Ask Muuttobotti AI</button></p></div><div className="faq-list">{faqs[locale].map(([question, answer], i) => <article key={i}><button onClick={() => setFaqOpen(faqOpen === i ? null : i)} aria-expanded={faqOpen === i}><span>{question}</span><ChevronDown className={faqOpen === i ? "rotate" : ""}/></button><AnimatePresence>{faqOpen === i && <motion.p initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}} exit={{opacity:0,height:0}}>{answer}</motion.p>}</AnimatePresence></article>)}</div></section>

      <section className="contact-section"><div className="map-card"><iframe title="Muuttobotti service area map" loading="lazy" referrerPolicy="no-referrer-when-downgrade" src="https://www.google.com/maps?q=Uusimaa%2C%20Finland&z=8&output=embed"/></div><div className="contact-copy"><span className="kicker">HELSINKI · UUSIMAA · FINLAND</span><h2>{u.contactTitle}</h2><p>{u.contactText}</p><div className="contact-actions"><a href="tel:+358400000000"><Phone/> +358 40 000 0000</a><a href="https://wa.me/358400000000"><MessageCircle/> WhatsApp</a></div><div className="hours"><Clock3/><div><strong>Mon–Sun</strong><span>07:00–22:00 · Emergency service available</span></div></div></div></section>

      <footer><div className="footer-brand"><div className="brand"><span className="brand-mark"><PackageCheck/></span><span>muutto<span>botti</span></span></div><p>Moving life forward — safely, simply and on time.</p><div className="footer-rating"><Star/> 4.9 on Google</div></div><div><strong>Services</strong><a href="#services">Moving</a><a href="#services">Transport</a><a href="#services">Cleaning</a><a href="#services">Window cleaning</a><a href="#services">Assembly</a></div><div><strong>Cities</strong>{["Helsinki", "Espoo", "Vantaa", "Tuusula", "Kerava", "Järvenpää", "Porvoo"].map(city => <a key={city} href={`/moving-${city.toLowerCase().replace("ä","a")}`}>{city}</a>)}</div><div><strong>Company</strong><a href="#booking">Book online</a><a href="#reviews">Reviews</a><a href="#faq">FAQ</a><a href="/privacy">Privacy</a><a href="/terms">Terms & cookies</a></div><div className="footer-bottom"><span>© 2026 Muuttobotti · Autochemix Oy · Y-tunnus 3543357-8</span><span>Made for moving forward.</span></div></footer>

      <button className="whatsapp-float" onClick={() => window.open("https://wa.me/358400000000", "_blank")} aria-label="Contact on WhatsApp"><MessageCircle/><span>WhatsApp</span></button>
      <button className="ai-float" onClick={() => setChatOpen(!chatOpen)} aria-label="Open smart assistant">{chatOpen ? <X/> : <Sparkles/>}</button>
      <AnimatePresence>{chatOpen && <motion.div className="ai-chat" initial={{opacity:0,y:16,scale:.96}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:16,scale:.96}}><div className="ai-head"><span><Sparkles/> Muuttobotti AI</span><i>Online</i></div><p>{u.aiHello}</p><div className="ai-options">{u.aiOptions.map(option => <button key={option} onClick={() => setChatReply(true)}>{option}<ChevronRight/></button>)}</div>{chatReply && <motion.p className="ai-response" initial={{opacity:0}} animate={{opacity:1}}>{u.aiReply}</motion.p>}</motion.div>}</AnimatePresence>
      <AnimatePresence>{cookie === null && <motion.div className="cookie-banner" initial={{y:30,opacity:0}} animate={{y:0,opacity:1}} exit={{y:30,opacity:0}}><ShieldCheck/><p>{u.cookies}</p><button onClick={() => acceptCookies("essential")}>{u.essential}</button><button className="cookie-accept" onClick={() => acceptCookies("all")}>{u.accept}</button></motion.div>}</AnimatePresence>
      <AnimatePresence>{bookingState === "done" && <motion.div className="success-overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div initial={{scale:.9,y:20}} animate={{scale:1,y:0}}><CheckCircle2/><h3>{u.success}</h3><p>{u.successText}</p><button onClick={() => setBookingState("idle")}>OK</button></motion.div></motion.div>}</AnimatePresence>
    </main>
  );
}
