import { useCallback, useState } from 'react';
import { router, useFocusEffect } from 'expo-router';
import { Alert, Linking, Platform, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Booking, getClientAccount, logoutClientAccount, registerAccountPush, registerBookingPush } from '../api';
import { localeOptions, useLanguage } from '../i18n';
import { registerForNotifications } from '../notifications';
import { SavedBookingCredential, secureStorage } from '../storage';
import { colors, radius } from '../theme';

const copy:any={
fi:{account:'Muuttobotti-tili',local:'Tällä laitteella',none:'Ei aktiivista varausta',logout:'Kirjaudu ulos',remove:'Poista',clear:'Poista paikalliset varaukset',pushOn:'Push-ilmoitukset ovat käytössä',pushOff:'Push-ilmoituksia ei ole vielä otettu käyttöön',pushMissing:'Remote push vaatii vielä Expo/EAS push -projektin.',version:'Muuttobotti Mobile v2.2.1',orders:'Omat tilaukset',noAccount:'Kirjaudu sähköpostilla etusivulta nähdäksesi kaikki tilauksesi.',session:'SUOJATTU ISTUNTO',help:'Tuki'},
en:{account:'Muuttobotti account',local:'On this device',none:'No active booking',logout:'Sign out',remove:'Remove',clear:'Clear local bookings',pushOn:'Push notifications are enabled',pushOff:'Push notifications are not enabled yet',pushMissing:'Remote push still requires an Expo/EAS push project.',version:'Muuttobotti Mobile v2.2.1',orders:'My orders',noAccount:'Sign in with email on the start screen to see all your orders.',session:'SECURE SESSION',help:'Support'},
ru:{account:'Аккаунт Muuttobotti',local:'На этом устройстве',none:'Нет активного заказа',logout:'Выйти',remove:'Удалить',clear:'Удалить локальные заказы',pushOn:'Push-уведомления включены',pushOff:'Push-уведомления ещё не включены',pushMissing:'Для удалённых push ещё нужен Expo/EAS push-проект.',version:'Muuttobotti Mobile v2.2.1',orders:'Мои заказы',noAccount:'Войдите по email на стартовом экране, чтобы видеть все свои заказы.',session:'ЗАЩИЩЁННАЯ СЕССИЯ',help:'Поддержка'},
uk:{account:'Акаунт Muuttobotti',local:'На цьому пристрої',none:'Немає активного замовлення',logout:'Вийти',remove:'Видалити',clear:'Видалити локальні замовлення',pushOn:'Push-сповіщення увімкнені',pushOff:'Push-сповіщення ще не увімкнені',pushMissing:'Для remote push ще потрібен Expo/EAS push-проєкт.',version:'Muuttobotti Mobile v2.2.1',orders:'Мої замовлення',noAccount:'Увійдіть через email на стартовому екрані, щоб бачити всі замовлення.',session:'ЗАХИЩЕНА СЕСІЯ',help:'Підтримка'}};

export default function ClientProfileScreen(){
 const {locale,setLocale,tr}=useLanguage();const t=copy[locale]||copy.fi;
 const[history,setHistory]=useState<SavedBookingCredential[]>([]);const[activeId,setActiveId]=useState('');const[pushEnabled,setPushEnabled]=useState(false);const[pushState,setPushState]=useState('');const[sessionEmail,setSessionEmail]=useState('');const[sessionToken,setSessionToken]=useState('');const[accountBookings,setAccountBookings]=useState<Booking[]>([]);const[busy,setBusy]=useState(false);

 const refresh=useCallback(async()=>{const[items,current,pushToken,session]=await Promise.all([secureStorage.getClientHistory(),secureStorage.getClientCredentials(),secureStorage.getPushToken(),secureStorage.getClientSession()]);setHistory(items);setActiveId(current.id);setPushEnabled(Boolean(pushToken));setSessionEmail(session.email);setSessionToken(session.token);if(session.token){try{const account=await getClientAccount(session.token);setAccountBookings(account.bookings||[])}catch(error){const text=error instanceof Error?error.message:'';if(/SESSION_INVALID|401/i.test(text)){await secureStorage.clearClientSession();setSessionEmail('');setSessionToken('')}setAccountBookings([])}}else setAccountBookings([])},[]);
 useFocusEffect(useCallback(()=>{void refresh()},[refresh]));

 const enablePush=async()=>{const result=await registerForNotifications();if(!result.ok){setPushState(result.reason==='REMOTE_PUSH_NOT_CONFIGURED'?t.pushMissing:tr('notificationUnavailable'));return}try{const[current,session]=await Promise.all([secureStorage.getClientCredentials(),secureStorage.getClientSession()]);if(session.token&&accountBookings.length){await Promise.all(accountBookings.slice(0,20).map(item=>registerAccountPush(session.token,item.id,result.token,Platform.OS,locale).catch(()=>null)))}else if(current.id&&current.key){await registerBookingPush(current.id,current.key,result.token,Platform.OS,locale)}}catch{}setPushState(tr('notificationReady'));await refresh()};

 const signOut=async()=>{if(busy)return;setBusy(true);try{if(sessionToken)await logoutClientAccount(sessionToken).catch(()=>null)}finally{await Promise.all([secureStorage.clearClientCredentials(),secureStorage.clearClientSession(),secureStorage.clearPushToken()]);setSessionEmail('');setSessionToken('');setAccountBookings([]);setHistory([]);setActiveId('');setBusy(false);if(Platform.OS==='web'&&typeof window!=='undefined'){window.location.replace('/app-preview/');return;}try{router.dismissAll()}catch{}router.replace('/')}};
 const removeBooking=async(id:string)=>{await secureStorage.removeClientCredential(id);await refresh()};
 const clearBookings=()=>Alert.alert(t.clear,'',[{text:'Cancel',style:'cancel'},{text:t.clear,style:'destructive',onPress:async()=>{await secureStorage.clearClientHistory();await refresh()}}]);

 return <ScrollView contentContainerStyle={s.wrap} showsVerticalScrollIndicator={false}>
  <View style={s.hero}><View style={s.live}><View style={s.dot}/><Text style={s.liveText}>CLIENT HUB · V2.2</Text></View><Text style={s.title}>{tr('profile')}</Text><Text style={s.copy}>{sessionEmail||tr('privacyCopy')}</Text>{sessionToken&&<Text style={s.secure}>{t.session}</Text>}</View>

  <View style={s.section}><Text style={s.sectionTitle}>{t.account}</Text>{sessionEmail?<><Text style={s.email}>{sessionEmail}</Text><Text style={s.small}>{accountBookings.length} {t.orders.toLowerCase()}</Text></>:<Text style={s.muted}>{t.noAccount}</Text>}<TouchableOpacity disabled={busy} style={s.logout} onPress={()=>void signOut()}><Text style={s.logoutText}>{busy?'…':t.logout}</Text></TouchableOpacity></View>

  {sessionEmail&&<View style={s.section}><Text style={s.sectionTitle}>{t.orders}</Text>{accountBookings.length===0?<Text style={s.muted}>—</Text>:accountBookings.map(item=><TouchableOpacity key={item.id} style={s.order} onPress={()=>router.push({pathname:'/account-order',params:{id:item.id}})}><View style={{flex:1}}><Text style={s.orderId}>{item.id}</Text><Text style={s.orderTitle}>{item.pickup} → {item.destination}</Text><Text style={s.orderMeta}>{item.preferred_date} {item.preferred_time} · {item.status}</Text></View>{Number(item.quoted_price||0)>0&&<Text style={s.price}>{Number(item.quoted_price).toFixed(0)} €</Text>}<Text style={s.arrow}>→</Text></TouchableOpacity>)}</View>}

  <View style={s.section}><Text style={s.sectionTitle}>{tr('language')}</Text><View style={s.langRow}>{localeOptions.map(item=><TouchableOpacity key={item.value} style={[s.lang,locale===item.value&&s.langActive]} onPress={()=>setLocale(item.value)}><Text style={[s.langText,locale===item.value&&s.langTextActive]}>{item.label}</Text></TouchableOpacity>)}</View></View>

  <View style={s.section}><Text style={s.sectionTitle}>{t.local}</Text><Text style={s.small}>{activeId||t.none}</Text>{history.map(item=><View key={item.id} style={s.localOrder}><TouchableOpacity style={s.localMain} onPress={()=>router.push({pathname:'/(client)/track',params:{id:item.id,key:item.key}})}><Text style={s.orderId}>{item.id}</Text><Text style={s.arrow}>→</Text></TouchableOpacity><TouchableOpacity style={s.remove} onPress={()=>void removeBooking(item.id)}><Text style={s.removeText}>{t.remove}</Text></TouchableOpacity></View>)}{history.length>0&&<TouchableOpacity style={s.danger} onPress={clearBookings}><Text style={s.dangerText}>{t.clear}</Text></TouchableOpacity>}</View>

  <View style={s.section}><Text style={s.sectionTitle}>{tr('notifications')}</Text><Text style={s.muted}>{pushState||(pushEnabled?t.pushOn:t.pushOff)}</Text><TouchableOpacity style={s.primary} onPress={()=>void enablePush()}><Text style={s.primaryText}>{tr('enableNotifications')}</Text></TouchableOpacity></View>

  <View style={s.section}><Text style={s.sectionTitle}>{t.help}</Text><TouchableOpacity style={s.action} onPress={()=>void Linking.openURL('tel:+3584578767567')}><Text style={s.actionText}>045 787 67567</Text></TouchableOpacity><TouchableOpacity style={s.action} onPress={()=>void Linking.openURL('https://wa.me/3584578767567')}><Text style={s.actionText}>WhatsApp</Text></TouchableOpacity><TouchableOpacity style={s.action} onPress={()=>void Linking.openURL('mailto:autochemixfin@gmail.com')}><Text style={s.actionText}>autochemixfin@gmail.com</Text></TouchableOpacity></View>
  <Text style={s.version}>{t.version}</Text>
 </ScrollView>
}

const s=StyleSheet.create({wrap:{padding:16,paddingBottom:42,gap:12,backgroundColor:'#EEF3EE'},hero:{backgroundColor:'#06191F',borderRadius:radius.xl,padding:22},live:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:6,backgroundColor:'#13353D',borderRadius:999,paddingHorizontal:9,paddingVertical:5},dot:{width:6,height:6,borderRadius:6,backgroundColor:'#C8FF36'},liveText:{color:'#C8FF36',fontSize:9,fontWeight:'900'},title:{color:'#fff',fontSize:34,fontWeight:'900',marginTop:8},copy:{color:'#A8BEB9',fontSize:13,lineHeight:20,marginTop:6},secure:{color:'#71918A',fontSize:9,fontWeight:'900',letterSpacing:1,marginTop:12},section:{backgroundColor:'#fff',borderRadius:radius.lg,padding:16,borderWidth:1,borderColor:colors.line,gap:9},sectionTitle:{color:colors.ink,fontSize:18,fontWeight:'900'},email:{color:colors.ink,fontSize:15,fontWeight:'800'},small:{color:'#667A75',fontSize:12},muted:{color:colors.muted,fontSize:13,lineHeight:20},order:{flexDirection:'row',alignItems:'center',gap:8,borderTopWidth:1,borderTopColor:'#EEF1EE',paddingVertical:11},orderId:{color:'#6E817C',fontSize:10,fontWeight:'900',letterSpacing:.7},orderTitle:{color:colors.ink,fontSize:13,fontWeight:'800',marginTop:3},orderMeta:{color:colors.muted,fontSize:10,marginTop:3},price:{color:colors.ink,fontWeight:'900',fontSize:13},arrow:{color:colors.ink,fontSize:19},langRow:{flexDirection:'row',gap:6},lang:{flex:1,minHeight:44,borderRadius:12,backgroundColor:'#EEF2ED',alignItems:'center',justifyContent:'center'},langActive:{backgroundColor:'#06191F'},langText:{color:'#667773',fontSize:12,fontWeight:'900'},langTextActive:{color:'#fff'},localOrder:{borderTopWidth:1,borderTopColor:'#EEF1EE',paddingTop:7},localMain:{flexDirection:'row',justifyContent:'space-between',paddingVertical:6},remove:{alignSelf:'flex-start',backgroundColor:'#F4F1EF',paddingHorizontal:9,paddingVertical:6,borderRadius:9},removeText:{color:colors.danger,fontSize:10,fontWeight:'900'},primary:{minHeight:50,borderRadius:13,backgroundColor:'#C8FF36',alignItems:'center',justifyContent:'center'},primaryText:{color:colors.ink,fontWeight:'900'},logout:{minHeight:49,borderRadius:13,backgroundColor:'#06191F',alignItems:'center',justifyContent:'center'},logoutText:{color:'#fff',fontWeight:'900'},danger:{minHeight:43,borderRadius:12,backgroundColor:'#FFF0EF',alignItems:'center',justifyContent:'center'},dangerText:{color:colors.danger,fontSize:11,fontWeight:'900'},action:{minHeight:45,borderRadius:12,backgroundColor:'#F0F3EE',paddingHorizontal:13,justifyContent:'center'},actionText:{color:colors.ink,fontSize:13,fontWeight:'800'},version:{textAlign:'center',color:colors.muted,fontSize:10}})
